// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LALoDep.Controllers.Administration
{
    public partial class AdministrationController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdministrationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAgencyGroup()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAgencyGroup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveAgencyGroup()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveAgencyGroup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AgencyGroupAllocation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AgencyGroupAllocation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AspPageList()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AspPageList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SaveHelp()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveHelp);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InvoiceGenerateFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceGenerateFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult JudgeDeptTransfer()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.JudgeDeptTransfer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult JudgeDeptTransferSubmit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.JudgeDeptTransferSubmit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MergeTemplateAdmin()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MergeTemplateAdmin);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult MergeTemplateAdminCopy()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.MergeTemplateAdminCopy);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MyTraining()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyTraining);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetTrainingSummaryData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetTrainingSummaryData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetTrainingData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetTrainingData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult TrainingDelete()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.TrainingDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PredeterminedAnswersAddEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PredeterminedAnswersAddEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult PredeterminedAnswersAddEditSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PredeterminedAnswersAddEditSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult PredeterminedAnswerCopy()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PredeterminedAnswerCopy);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SystemLValueList()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SystemLValueList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SystemValuesAddEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SystemValuesAddEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Download()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Download);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdministrationController Actions { get { return MVC.Administration; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Administration";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Administration";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string AgencyGroup = "AgencyGroup";
            public readonly string GetAgencyGroup = "GetAgencyGroup";
            public readonly string SaveAgencyGroup = "SaveAgencyGroup";
            public readonly string AgencyGroupAllocation = "AgencyGroupAllocation";
            public readonly string HelpList = "HelpList";
            public readonly string HelpTree = "HelpTree";
            public readonly string AspPageList = "AspPageList";
            public readonly string SaveHelp = "SaveHelp";
            public readonly string ImportPaidInvoices = "ImportPaidInvoices";
            public readonly string InvoiceSummary = "InvoiceSummary";
            public readonly string InvoiceGenerateFile = "InvoiceGenerateFile";
            public readonly string JudgeDeptTransfer = "JudgeDeptTransfer";
            public readonly string JudgeDeptTransferSubmit = "JudgeDeptTransferSubmit";
            public readonly string MergeTemplateAdmin = "MergeTemplateAdmin";
            public readonly string MergeTemplateAdminCopy = "MergeTemplateAdminCopy";
            public readonly string MyTraining = "MyTraining";
            public readonly string GetTrainingSummaryData = "GetTrainingSummaryData";
            public readonly string GetTrainingData = "GetTrainingData";
            public readonly string TrainingDelete = "TrainingDelete";
            public readonly string PredeterminedAnswersList = "PredeterminedAnswersList";
            public readonly string PredeterminedAnswersAddEdit = "PredeterminedAnswersAddEdit";
            public readonly string PredeterminedAnswersAddEditSave = "PredeterminedAnswersAddEditSave";
            public readonly string PredeterminedAnswerCopy = "PredeterminedAnswerCopy";
            public readonly string SystemValues = "SystemValues";
            public readonly string SystemLValueList = "SystemLValueList";
            public readonly string SystemValuesAddEdit = "SystemValuesAddEdit";
            public readonly string ChangePassword = "ChangePassword";
            public readonly string Download = "Download";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string AgencyGroup = "AgencyGroup";
            public const string GetAgencyGroup = "GetAgencyGroup";
            public const string SaveAgencyGroup = "SaveAgencyGroup";
            public const string AgencyGroupAllocation = "AgencyGroupAllocation";
            public const string HelpList = "HelpList";
            public const string HelpTree = "HelpTree";
            public const string AspPageList = "AspPageList";
            public const string SaveHelp = "SaveHelp";
            public const string ImportPaidInvoices = "ImportPaidInvoices";
            public const string InvoiceSummary = "InvoiceSummary";
            public const string InvoiceGenerateFile = "InvoiceGenerateFile";
            public const string JudgeDeptTransfer = "JudgeDeptTransfer";
            public const string JudgeDeptTransferSubmit = "JudgeDeptTransferSubmit";
            public const string MergeTemplateAdmin = "MergeTemplateAdmin";
            public const string MergeTemplateAdminCopy = "MergeTemplateAdminCopy";
            public const string MyTraining = "MyTraining";
            public const string GetTrainingSummaryData = "GetTrainingSummaryData";
            public const string GetTrainingData = "GetTrainingData";
            public const string TrainingDelete = "TrainingDelete";
            public const string PredeterminedAnswersList = "PredeterminedAnswersList";
            public const string PredeterminedAnswersAddEdit = "PredeterminedAnswersAddEdit";
            public const string PredeterminedAnswersAddEditSave = "PredeterminedAnswersAddEditSave";
            public const string PredeterminedAnswerCopy = "PredeterminedAnswerCopy";
            public const string SystemValues = "SystemValues";
            public const string SystemLValueList = "SystemLValueList";
            public const string SystemValuesAddEdit = "SystemValuesAddEdit";
            public const string ChangePassword = "ChangePassword";
            public const string Download = "Download";
        }


        static readonly ActionParamsClass_GetAgencyGroup s_params_GetAgencyGroup = new ActionParamsClass_GetAgencyGroup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAgencyGroup GetAgencyGroupParams { get { return s_params_GetAgencyGroup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAgencyGroup
        {
            public readonly string id = "id";
            public readonly string agencyCountyId = "agencyCountyId";
        }
        static readonly ActionParamsClass_SaveAgencyGroup s_params_SaveAgencyGroup = new ActionParamsClass_SaveAgencyGroup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveAgencyGroup SaveAgencyGroupParams { get { return s_params_SaveAgencyGroup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveAgencyGroup
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AgencyGroupAllocation s_params_AgencyGroupAllocation = new ActionParamsClass_AgencyGroupAllocation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AgencyGroupAllocation AgencyGroupAllocationParams { get { return s_params_AgencyGroupAllocation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AgencyGroupAllocation
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_AspPageList s_params_AspPageList = new ActionParamsClass_AspPageList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AspPageList AspPageListParams { get { return s_params_AspPageList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AspPageList
        {
            public readonly string helpID = "helpID";
        }
        static readonly ActionParamsClass_SaveHelp s_params_SaveHelp = new ActionParamsClass_SaveHelp();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveHelp SaveHelpParams { get { return s_params_SaveHelp; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveHelp
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ImportPaidInvoices s_params_ImportPaidInvoices = new ActionParamsClass_ImportPaidInvoices();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ImportPaidInvoices ImportPaidInvoicesParams { get { return s_params_ImportPaidInvoices; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ImportPaidInvoices
        {
            public readonly string form = "form";
        }
        static readonly ActionParamsClass_InvoiceSummary s_params_InvoiceSummary = new ActionParamsClass_InvoiceSummary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InvoiceSummary InvoiceSummaryParams { get { return s_params_InvoiceSummary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InvoiceSummary
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_InvoiceGenerateFile s_params_InvoiceGenerateFile = new ActionParamsClass_InvoiceGenerateFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InvoiceGenerateFile InvoiceGenerateFileParams { get { return s_params_InvoiceGenerateFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InvoiceGenerateFile
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_JudgeDeptTransfer s_params_JudgeDeptTransfer = new ActionParamsClass_JudgeDeptTransfer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_JudgeDeptTransfer JudgeDeptTransferParams { get { return s_params_JudgeDeptTransfer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_JudgeDeptTransfer
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_JudgeDeptTransferSubmit s_params_JudgeDeptTransferSubmit = new ActionParamsClass_JudgeDeptTransferSubmit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_JudgeDeptTransferSubmit JudgeDeptTransferSubmitParams { get { return s_params_JudgeDeptTransferSubmit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_JudgeDeptTransferSubmit
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_MergeTemplateAdmin s_params_MergeTemplateAdmin = new ActionParamsClass_MergeTemplateAdmin();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MergeTemplateAdmin MergeTemplateAdminParams { get { return s_params_MergeTemplateAdmin; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MergeTemplateAdmin
        {
            public readonly string id = "id";
            public readonly string AgencyID = "AgencyID";
        }
        static readonly ActionParamsClass_MergeTemplateAdminCopy s_params_MergeTemplateAdminCopy = new ActionParamsClass_MergeTemplateAdminCopy();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MergeTemplateAdminCopy MergeTemplateAdminCopyParams { get { return s_params_MergeTemplateAdminCopy; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MergeTemplateAdminCopy
        {
            public readonly string id = "id";
            public readonly string AgencyID = "AgencyID";
        }
        static readonly ActionParamsClass_MyTraining s_params_MyTraining = new ActionParamsClass_MyTraining();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyTraining MyTrainingParams { get { return s_params_MyTraining; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyTraining
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetTrainingSummaryData s_params_GetTrainingSummaryData = new ActionParamsClass_GetTrainingSummaryData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTrainingSummaryData GetTrainingSummaryDataParams { get { return s_params_GetTrainingSummaryData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTrainingSummaryData
        {
            public readonly string parameters = "parameters";
        }
        static readonly ActionParamsClass_GetTrainingData s_params_GetTrainingData = new ActionParamsClass_GetTrainingData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTrainingData GetTrainingDataParams { get { return s_params_GetTrainingData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTrainingData
        {
            public readonly string parameters = "parameters";
        }
        static readonly ActionParamsClass_TrainingDelete s_params_TrainingDelete = new ActionParamsClass_TrainingDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TrainingDelete TrainingDeleteParams { get { return s_params_TrainingDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TrainingDelete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PredeterminedAnswersList s_params_PredeterminedAnswersList = new ActionParamsClass_PredeterminedAnswersList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PredeterminedAnswersList PredeterminedAnswersListParams { get { return s_params_PredeterminedAnswersList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PredeterminedAnswersList
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_PredeterminedAnswersAddEdit s_params_PredeterminedAnswersAddEdit = new ActionParamsClass_PredeterminedAnswersAddEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PredeterminedAnswersAddEdit PredeterminedAnswersAddEditParams { get { return s_params_PredeterminedAnswersAddEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PredeterminedAnswersAddEdit
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PredeterminedAnswersAddEditSave s_params_PredeterminedAnswersAddEditSave = new ActionParamsClass_PredeterminedAnswersAddEditSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PredeterminedAnswersAddEditSave PredeterminedAnswersAddEditSaveParams { get { return s_params_PredeterminedAnswersAddEditSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PredeterminedAnswersAddEditSave
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_PredeterminedAnswerCopy s_params_PredeterminedAnswerCopy = new ActionParamsClass_PredeterminedAnswerCopy();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PredeterminedAnswerCopy PredeterminedAnswerCopyParams { get { return s_params_PredeterminedAnswerCopy; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PredeterminedAnswerCopy
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SystemLValueList s_params_SystemLValueList = new ActionParamsClass_SystemLValueList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SystemLValueList SystemLValueListParams { get { return s_params_SystemLValueList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SystemLValueList
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SystemValuesAddEdit s_params_SystemValuesAddEdit = new ActionParamsClass_SystemValuesAddEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SystemValuesAddEdit SystemValuesAddEditParams { get { return s_params_SystemValuesAddEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SystemValuesAddEdit
        {
            public readonly string id = "id";
            public readonly string systemValueTypeEntry = "systemValueTypeEntry";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ChangePassword s_params_ChangePassword = new ActionParamsClass_ChangePassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePassword ChangePasswordParams { get { return s_params_ChangePassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePassword
        {
            public readonly string changePasswordViewModel = "changePasswordViewModel";
        }
        static readonly ActionParamsClass_Download s_params_Download = new ActionParamsClass_Download();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Download DownloadParams { get { return s_params_Download; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Download
        {
            public readonly string file = "file";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AgencyGroupPartial = "_AgencyGroupPartial";
                public readonly string _JudgeDeptTransferSearchResult = "_JudgeDeptTransferSearchResult";
                public readonly string _myTraining = "_myTraining";
                public readonly string AgencyGroup = "AgencyGroup";
                public readonly string AgencyGroupAllocation = "AgencyGroupAllocation";
                public readonly string ChangePassword = "ChangePassword";
                public readonly string HelpList = "HelpList";
                public readonly string ImportPaidInvoices = "ImportPaidInvoices";
                public readonly string InvoiceSummary = "InvoiceSummary";
                public readonly string JudgeDeptTransfer = "JudgeDeptTransfer";
                public readonly string MergeTemplateAdmin = "MergeTemplateAdmin";
                public readonly string MyTraining = "MyTraining";
                public readonly string PredeterminedAnswersAddEdit = "PredeterminedAnswersAddEdit";
                public readonly string PredeterminedAnswersList = "PredeterminedAnswersList";
                public readonly string SystemValues = "SystemValues";
                public readonly string SystemValuesAddEdit = "SystemValuesAddEdit";
            }
            public readonly string _AgencyGroupPartial = "~/Views/Administration/_AgencyGroupPartial.cshtml";
            public readonly string _JudgeDeptTransferSearchResult = "~/Views/Administration/_JudgeDeptTransferSearchResult.cshtml";
            public readonly string _myTraining = "~/Views/Administration/_myTraining.cshtml";
            public readonly string AgencyGroup = "~/Views/Administration/AgencyGroup.cshtml";
            public readonly string AgencyGroupAllocation = "~/Views/Administration/AgencyGroupAllocation.cshtml";
            public readonly string ChangePassword = "~/Views/Administration/ChangePassword.cshtml";
            public readonly string HelpList = "~/Views/Administration/HelpList.cshtml";
            public readonly string ImportPaidInvoices = "~/Views/Administration/ImportPaidInvoices.cshtml";
            public readonly string InvoiceSummary = "~/Views/Administration/InvoiceSummary.cshtml";
            public readonly string JudgeDeptTransfer = "~/Views/Administration/JudgeDeptTransfer.cshtml";
            public readonly string MergeTemplateAdmin = "~/Views/Administration/MergeTemplateAdmin.cshtml";
            public readonly string MyTraining = "~/Views/Administration/MyTraining.cshtml";
            public readonly string PredeterminedAnswersAddEdit = "~/Views/Administration/PredeterminedAnswersAddEdit.cshtml";
            public readonly string PredeterminedAnswersList = "~/Views/Administration/PredeterminedAnswersList.cshtml";
            public readonly string SystemValues = "~/Views/Administration/SystemValues.cshtml";
            public readonly string SystemValuesAddEdit = "~/Views/Administration/SystemValuesAddEdit.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdministrationController : LALoDep.Controllers.Administration.AdministrationController
    {
        public T4MVC_AdministrationController() : base(Dummy.Instance) { }

        [NonAction]
        partial void AgencyGroupOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AgencyGroup()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AgencyGroup);
            AgencyGroupOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAgencyGroupOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? id, int? agencyCountyId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAgencyGroup(int? id, int? agencyCountyId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAgencyGroup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "agencyCountyId", agencyCountyId);
            GetAgencyGroupOverride(callInfo, id, agencyCountyId);
            return callInfo;
        }

        [NonAction]
        partial void SaveAgencyGroupOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Administration.AgencyGroupViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveAgencyGroup(LALoDep.Models.Administration.AgencyGroupViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveAgencyGroup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            SaveAgencyGroupOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void AgencyGroupAllocationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AgencyGroupAllocation(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AgencyGroupAllocation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AgencyGroupAllocationOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AgencyGroupAllocationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<LALoDep.Domain.TitleIVe.TitleIVeAgencyGroupCountyAllocationGet_spResult> viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult AgencyGroupAllocation(System.Collections.Generic.List<LALoDep.Domain.TitleIVe.TitleIVeAgencyGroupCountyAllocationGet_spResult> viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AgencyGroupAllocation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AgencyGroupAllocationOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void HelpListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult HelpList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HelpList);
            HelpListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HelpTreeOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult HelpTree()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.HelpTree);
            HelpTreeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AspPageListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int? helpID);

        [NonAction]
        public override System.Web.Mvc.JsonResult AspPageList(int? helpID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AspPageList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "helpID", helpID);
            AspPageListOverride(callInfo, helpID);
            return callInfo;
        }

        [NonAction]
        partial void SaveHelpOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.HelpAddEditViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult SaveHelp(LALoDep.Models.HelpAddEditViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveHelp);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            SaveHelpOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void ImportPaidInvoicesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ImportPaidInvoices()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ImportPaidInvoices);
            ImportPaidInvoicesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ImportPaidInvoicesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection form);

        [NonAction]
        public override System.Web.Mvc.ActionResult ImportPaidInvoices(System.Web.Mvc.FormCollection form)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ImportPaidInvoices);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "form", form);
            ImportPaidInvoicesOverride(callInfo, form);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceSummary()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceSummary);
            InvoiceSummaryOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Administration.InvoiceSummaryViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceSummary(LALoDep.Models.Administration.InvoiceSummaryViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceSummary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            InvoiceSummaryOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceGenerateFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceGenerateFile(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceGenerateFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            InvoiceGenerateFileOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void JudgeDeptTransferOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult JudgeDeptTransfer(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.JudgeDeptTransfer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            JudgeDeptTransferOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void JudgeDeptTransferOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Administration.JudgeDeptTransferViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult JudgeDeptTransfer(LALoDep.Models.Administration.JudgeDeptTransferViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.JudgeDeptTransfer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            JudgeDeptTransferOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void JudgeDeptTransferSubmitOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Administration.JudgeDeptTransferViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult JudgeDeptTransferSubmit(LALoDep.Models.Administration.JudgeDeptTransferViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.JudgeDeptTransferSubmit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            JudgeDeptTransferSubmitOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void MergeTemplateAdminOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult MergeTemplateAdmin(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MergeTemplateAdmin);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            MergeTemplateAdminOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void MergeTemplateAdminOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int? AgencyID);

        [NonAction]
        public override System.Web.Mvc.JsonResult MergeTemplateAdmin(int? AgencyID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.MergeTemplateAdmin);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AgencyID", AgencyID);
            MergeTemplateAdminOverride(callInfo, AgencyID);
            return callInfo;
        }

        [NonAction]
        partial void MergeTemplateAdminCopyOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id, int? AgencyID);

        [NonAction]
        public override System.Web.Mvc.JsonResult MergeTemplateAdminCopy(string id, int? AgencyID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.MergeTemplateAdminCopy);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AgencyID", AgencyID);
            MergeTemplateAdminCopyOverride(callInfo, id, AgencyID);
            return callInfo;
        }

        [NonAction]
        partial void MyTrainingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyTraining(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyTraining);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            MyTrainingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GetTrainingSummaryDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Administration.TrainingViewModel parameters);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetTrainingSummaryData(LALoDep.Models.Administration.TrainingViewModel parameters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetTrainingSummaryData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parameters", parameters);
            GetTrainingSummaryDataOverride(callInfo, parameters);
            return callInfo;
        }

        [NonAction]
        partial void GetTrainingDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Administration.TrainingViewModel parameters);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetTrainingData(LALoDep.Models.Administration.TrainingViewModel parameters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetTrainingData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parameters", parameters);
            GetTrainingDataOverride(callInfo, parameters);
            return callInfo;
        }

        [NonAction]
        partial void TrainingDeleteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult TrainingDelete(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.TrainingDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TrainingDeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PredeterminedAnswersListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PredeterminedAnswersList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PredeterminedAnswersList);
            PredeterminedAnswersListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PredeterminedAnswersListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Administration.PredeterminedAnswersViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult PredeterminedAnswersList(LALoDep.Models.Administration.PredeterminedAnswersViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PredeterminedAnswersList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            PredeterminedAnswersListOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void PredeterminedAnswersAddEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PredeterminedAnswersAddEdit(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PredeterminedAnswersAddEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PredeterminedAnswersAddEditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PredeterminedAnswersAddEditSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Administration.PredeterminedAnswersAddEditModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult PredeterminedAnswersAddEditSave(LALoDep.Models.Administration.PredeterminedAnswersAddEditModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PredeterminedAnswersAddEditSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PredeterminedAnswersAddEditSaveOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PredeterminedAnswerCopyOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult PredeterminedAnswerCopy(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PredeterminedAnswerCopy);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PredeterminedAnswerCopyOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SystemValuesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SystemValues()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SystemValues);
            SystemValuesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SystemLValueListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult SystemLValueList(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SystemLValueList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SystemLValueListOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SystemValuesAddEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string systemValueTypeEntry);

        [NonAction]
        public override System.Web.Mvc.ActionResult SystemValuesAddEdit(string id, string systemValueTypeEntry)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SystemValuesAddEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "systemValueTypeEntry", systemValueTypeEntry);
            SystemValuesAddEditOverride(callInfo, id, systemValueTypeEntry);
            return callInfo;
        }

        [NonAction]
        partial void SystemValuesAddEditOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Administration.AdminSystemValueUpdateViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult SystemValuesAddEdit(LALoDep.Models.Administration.AdminSystemValueUpdateViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SystemValuesAddEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            SystemValuesAddEditOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ChangePasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Administration.AdminChangePasswordViewModel changePasswordViewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult ChangePassword(LALoDep.Models.Administration.AdminChangePasswordViewModel changePasswordViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ChangePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "changePasswordViewModel", changePasswordViewModel);
            ChangePasswordOverride(callInfo, changePasswordViewModel);
            return callInfo;
        }

        [NonAction]
        partial void DownloadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string file);

        [NonAction]
        public override System.Web.Mvc.ActionResult Download(string file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Download);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            DownloadOverride(callInfo, file);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
