// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LALoDep.Controllers.CaseOpening
{
    public partial class CaseOpeningController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CaseOpeningController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ActionRequestDelete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActionRequestDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ActionRequestPrint()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActionRequestPrint);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddCaseRespondents()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddCaseRespondents);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AssociationSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AssociationSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AssociationDelete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AssociationDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CaseAddresses()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseAddresses);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CaseAddressEdit()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CaseAddressEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CaseAddressDelete()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CaseAddressDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CaseAddressesPrint()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseAddressesPrint);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult InsertCase()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.InsertCase);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Hearing()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hearing);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult HearingSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.HearingSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult HearingDelete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult HearingUpdate()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.HearingUpdate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult LegalNumberSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LegalNumberSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult LegalPartiesSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LegalPartiesSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult NoteSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NoteSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PetitionEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PetitionSave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PetitionDelete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PetitionCopy()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionCopy);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CaseOpeningController Actions { get { return MVC.CaseOpening; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "CaseOpening";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "CaseOpening";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ActionRequest = "ActionRequest";
            public readonly string ActionRequestDelete = "ActionRequestDelete";
            public readonly string ActionRequestPrint = "ActionRequestPrint";
            public readonly string ActionRequestAdd = "ActionRequestAdd";
            public readonly string AddCaseRespondents = "AddCaseRespondents";
            public readonly string Associations = "Associations";
            public readonly string AssociationSave = "AssociationSave";
            public readonly string AssociationDelete = "AssociationDelete";
            public readonly string CaseAddresses = "CaseAddresses";
            public readonly string CaseAddressEdit = "CaseAddressEdit";
            public readonly string CaseAddressDelete = "CaseAddressDelete";
            public readonly string CaseAddressesPrint = "CaseAddressesPrint";
            public readonly string AddApptCase = "AddApptCase";
            public readonly string InsertCase = "InsertCase";
            public readonly string Hearing = "Hearing";
            public readonly string HearingSave = "HearingSave";
            public readonly string HearingDelete = "HearingDelete";
            public readonly string HearingUpdate = "HearingUpdate";
            public readonly string LegalNumbers = "LegalNumbers";
            public readonly string LegalNumberSave = "LegalNumberSave";
            public readonly string LegalParties = "LegalParties";
            public readonly string LegalPartiesSave = "LegalPartiesSave";
            public readonly string Notes = "Notes";
            public readonly string NoteSave = "NoteSave";
            public readonly string PetitionList = "PetitionList";
            public readonly string PetitionAdd = "PetitionAdd";
            public readonly string PetitionEdit = "PetitionEdit";
            public readonly string PetitionSave = "PetitionSave";
            public readonly string PetitionDelete = "PetitionDelete";
            public readonly string PetitionCopy = "PetitionCopy";
            public readonly string EditAllegationFinding = "EditAllegationFinding";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ActionRequest = "ActionRequest";
            public const string ActionRequestDelete = "ActionRequestDelete";
            public const string ActionRequestPrint = "ActionRequestPrint";
            public const string ActionRequestAdd = "ActionRequestAdd";
            public const string AddCaseRespondents = "AddCaseRespondents";
            public const string Associations = "Associations";
            public const string AssociationSave = "AssociationSave";
            public const string AssociationDelete = "AssociationDelete";
            public const string CaseAddresses = "CaseAddresses";
            public const string CaseAddressEdit = "CaseAddressEdit";
            public const string CaseAddressDelete = "CaseAddressDelete";
            public const string CaseAddressesPrint = "CaseAddressesPrint";
            public const string AddApptCase = "AddApptCase";
            public const string InsertCase = "InsertCase";
            public const string Hearing = "Hearing";
            public const string HearingSave = "HearingSave";
            public const string HearingDelete = "HearingDelete";
            public const string HearingUpdate = "HearingUpdate";
            public const string LegalNumbers = "LegalNumbers";
            public const string LegalNumberSave = "LegalNumberSave";
            public const string LegalParties = "LegalParties";
            public const string LegalPartiesSave = "LegalPartiesSave";
            public const string Notes = "Notes";
            public const string NoteSave = "NoteSave";
            public const string PetitionList = "PetitionList";
            public const string PetitionAdd = "PetitionAdd";
            public const string PetitionEdit = "PetitionEdit";
            public const string PetitionSave = "PetitionSave";
            public const string PetitionDelete = "PetitionDelete";
            public const string PetitionCopy = "PetitionCopy";
            public const string EditAllegationFinding = "EditAllegationFinding";
        }


        static readonly ActionParamsClass_ActionRequestDelete s_params_ActionRequestDelete = new ActionParamsClass_ActionRequestDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActionRequestDelete ActionRequestDeleteParams { get { return s_params_ActionRequestDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActionRequestDelete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ActionRequestPrint s_params_ActionRequestPrint = new ActionParamsClass_ActionRequestPrint();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActionRequestPrint ActionRequestPrintParams { get { return s_params_ActionRequestPrint; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActionRequestPrint
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ActionRequestAdd s_params_ActionRequestAdd = new ActionParamsClass_ActionRequestAdd();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActionRequestAdd ActionRequestAddParams { get { return s_params_ActionRequestAdd; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActionRequestAdd
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddCaseRespondents s_params_AddCaseRespondents = new ActionParamsClass_AddCaseRespondents();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddCaseRespondents AddCaseRespondentsParams { get { return s_params_AddCaseRespondents; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddCaseRespondents
        {
            public readonly string dataentry = "dataentry";
            public readonly string respondents = "respondents";
        }
        static readonly ActionParamsClass_AssociationSave s_params_AssociationSave = new ActionParamsClass_AssociationSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AssociationSave AssociationSaveParams { get { return s_params_AssociationSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AssociationSave
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AssociationDelete s_params_AssociationDelete = new ActionParamsClass_AssociationDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AssociationDelete AssociationDeleteParams { get { return s_params_AssociationDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AssociationDelete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CaseAddresses s_params_CaseAddresses = new ActionParamsClass_CaseAddresses();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CaseAddresses CaseAddressesParams { get { return s_params_CaseAddresses; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CaseAddresses
        {
            public readonly string addressId = "addressId";
            public readonly string model = "model";
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_CaseAddressEdit s_params_CaseAddressEdit = new ActionParamsClass_CaseAddressEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CaseAddressEdit CaseAddressEditParams { get { return s_params_CaseAddressEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CaseAddressEdit
        {
            public readonly string model = "model";
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_CaseAddressDelete s_params_CaseAddressDelete = new ActionParamsClass_CaseAddressDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CaseAddressDelete CaseAddressDeleteParams { get { return s_params_CaseAddressDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CaseAddressDelete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CaseAddressesPrint s_params_CaseAddressesPrint = new ActionParamsClass_CaseAddressesPrint();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CaseAddressesPrint CaseAddressesPrintParams { get { return s_params_CaseAddressesPrint; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CaseAddressesPrint
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddApptCase s_params_AddApptCase = new ActionParamsClass_AddApptCase();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddApptCase AddApptCaseParams { get { return s_params_AddApptCase; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddApptCase
        {
            public readonly string searchParams = "searchParams";
        }
        static readonly ActionParamsClass_InsertCase s_params_InsertCase = new ActionParamsClass_InsertCase();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InsertCase InsertCaseParams { get { return s_params_InsertCase; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InsertCase
        {
            public readonly string searchParams = "searchParams";
        }
        static readonly ActionParamsClass_Hearing s_params_Hearing = new ActionParamsClass_Hearing();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Hearing HearingParams { get { return s_params_Hearing; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Hearing
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_HearingSave s_params_HearingSave = new ActionParamsClass_HearingSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HearingSave HearingSaveParams { get { return s_params_HearingSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HearingSave
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_HearingDelete s_params_HearingDelete = new ActionParamsClass_HearingDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HearingDelete HearingDeleteParams { get { return s_params_HearingDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HearingDelete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_HearingUpdate s_params_HearingUpdate = new ActionParamsClass_HearingUpdate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HearingUpdate HearingUpdateParams { get { return s_params_HearingUpdate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HearingUpdate
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_LegalNumberSave s_params_LegalNumberSave = new ActionParamsClass_LegalNumberSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LegalNumberSave LegalNumberSaveParams { get { return s_params_LegalNumberSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LegalNumberSave
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_LegalPartiesSave s_params_LegalPartiesSave = new ActionParamsClass_LegalPartiesSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LegalPartiesSave LegalPartiesSaveParams { get { return s_params_LegalPartiesSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LegalPartiesSave
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_NoteSave s_params_NoteSave = new ActionParamsClass_NoteSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NoteSave NoteSaveParams { get { return s_params_NoteSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NoteSave
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_PetitionEdit s_params_PetitionEdit = new ActionParamsClass_PetitionEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PetitionEdit PetitionEditParams { get { return s_params_PetitionEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PetitionEdit
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PetitionSave s_params_PetitionSave = new ActionParamsClass_PetitionSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PetitionSave PetitionSaveParams { get { return s_params_PetitionSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PetitionSave
        {
            public readonly string model = "model";
            public readonly string oldModel = "oldModel";
        }
        static readonly ActionParamsClass_PetitionDelete s_params_PetitionDelete = new ActionParamsClass_PetitionDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PetitionDelete PetitionDeleteParams { get { return s_params_PetitionDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PetitionDelete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PetitionCopy s_params_PetitionCopy = new ActionParamsClass_PetitionCopy();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PetitionCopy PetitionCopyParams { get { return s_params_PetitionCopy; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PetitionCopy
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditAllegationFinding s_params_EditAllegationFinding = new ActionParamsClass_EditAllegationFinding();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditAllegationFinding EditAllegationFindingParams { get { return s_params_EditAllegationFinding; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditAllegationFinding
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _steps = "_steps";
                public readonly string ActionRequest = "ActionRequest";
                public readonly string ActionRequestAdd = "ActionRequestAdd";
                public readonly string AddApptCase = "AddApptCase";
                public readonly string AddCaseRespondents = "AddCaseRespondents";
                public readonly string Associations = "Associations";
                public readonly string CaseAddresses = "CaseAddresses";
                public readonly string EditAllegationFinding = "EditAllegationFinding";
                public readonly string Hearing = "Hearing";
                public readonly string HearingEdit = "HearingEdit";
                public readonly string LegalNumbers = "LegalNumbers";
                public readonly string LegalParties = "LegalParties";
                public readonly string Notes = "Notes";
                public readonly string PetitionAddEdit = "PetitionAddEdit";
                public readonly string PetitionCopy = "PetitionCopy";
                public readonly string PetitionList = "PetitionList";
            }
            public readonly string _steps = "~/Views/CaseOpening/_steps.cshtml";
            public readonly string ActionRequest = "~/Views/CaseOpening/ActionRequest.cshtml";
            public readonly string ActionRequestAdd = "~/Views/CaseOpening/ActionRequestAdd.cshtml";
            public readonly string AddApptCase = "~/Views/CaseOpening/AddApptCase.cshtml";
            public readonly string AddCaseRespondents = "~/Views/CaseOpening/AddCaseRespondents.cshtml";
            public readonly string Associations = "~/Views/CaseOpening/Associations.cshtml";
            public readonly string CaseAddresses = "~/Views/CaseOpening/CaseAddresses.cshtml";
            public readonly string EditAllegationFinding = "~/Views/CaseOpening/EditAllegationFinding.cshtml";
            public readonly string Hearing = "~/Views/CaseOpening/Hearing.cshtml";
            public readonly string HearingEdit = "~/Views/CaseOpening/HearingEdit.cshtml";
            public readonly string LegalNumbers = "~/Views/CaseOpening/LegalNumbers.cshtml";
            public readonly string LegalParties = "~/Views/CaseOpening/LegalParties.cshtml";
            public readonly string Notes = "~/Views/CaseOpening/Notes.cshtml";
            public readonly string PetitionAddEdit = "~/Views/CaseOpening/PetitionAddEdit.cshtml";
            public readonly string PetitionCopy = "~/Views/CaseOpening/PetitionCopy.cshtml";
            public readonly string PetitionList = "~/Views/CaseOpening/PetitionList.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CaseOpeningController : LALoDep.Controllers.CaseOpening.CaseOpeningController
    {
        public T4MVC_CaseOpeningController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ActionRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActionRequest()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActionRequest);
            ActionRequestOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ActionRequestDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActionRequestDelete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActionRequestDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ActionRequestDeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ActionRequestPrintOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActionRequestPrint(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActionRequestPrint);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ActionRequestPrintOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ActionRequestAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActionRequestAdd()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActionRequestAdd);
            ActionRequestAddOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ActionRequestAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.CaseOpening.ActionRequestAddModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult ActionRequestAdd(LALoDep.Models.CaseOpening.ActionRequestAddModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActionRequestAdd);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ActionRequestAddOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AddCaseRespondentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string dataentry);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddCaseRespondents(string dataentry)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddCaseRespondents);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dataentry", dataentry);
            AddCaseRespondentsOverride(callInfo, dataentry);
            return callInfo;
        }

        [NonAction]
        partial void AddCaseRespondentsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, System.Collections.Generic.List<LALoDep.Models.CaseOpening.AddChildOrParent> respondents);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddCaseRespondents(System.Collections.Generic.List<LALoDep.Models.CaseOpening.AddChildOrParent> respondents)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddCaseRespondents);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "respondents", respondents);
            AddCaseRespondentsOverride(callInfo, respondents);
            return callInfo;
        }

        [NonAction]
        partial void AssociationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Associations()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Associations);
            AssociationsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AssociationSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.AssociationsModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult AssociationSave(LALoDep.Models.CaseOpening.AssociationsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AssociationSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AssociationSaveOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AssociationDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AssociationDelete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AssociationDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AssociationDeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CaseAddressesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string addressId);

        [NonAction]
        public override System.Web.Mvc.ActionResult CaseAddresses(string addressId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseAddresses);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "addressId", addressId);
            CaseAddressesOverride(callInfo, addressId);
            return callInfo;
        }

        [NonAction]
        partial void CaseAddressesOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.CaseAddressesViewModel model, System.Web.Mvc.FormCollection collection);

        [NonAction]
        public override System.Web.Mvc.JsonResult CaseAddresses(LALoDep.Models.CaseOpening.CaseAddressesViewModel model, System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CaseAddresses);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            CaseAddressesOverride(callInfo, model, collection);
            return callInfo;
        }

        [NonAction]
        partial void CaseAddressEditOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.CaseAddressesViewModel model, System.Web.Mvc.FormCollection collection);

        [NonAction]
        public override System.Web.Mvc.JsonResult CaseAddressEdit(LALoDep.Models.CaseOpening.CaseAddressesViewModel model, System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CaseAddressEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            CaseAddressEditOverride(callInfo, model, collection);
            return callInfo;
        }

        [NonAction]
        partial void CaseAddressDeleteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult CaseAddressDelete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CaseAddressDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CaseAddressDeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CaseAddressesPrintOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.CaseOpening.CaseAddressesViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CaseAddressesPrint(LALoDep.Models.CaseOpening.CaseAddressesViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseAddressesPrint);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CaseAddressesPrintOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AddApptCaseOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddApptCase()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddApptCase);
            AddApptCaseOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddApptCaseOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.AddAppointmentCaseSearchViewModel searchParams);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddApptCase(LALoDep.Models.CaseOpening.AddAppointmentCaseSearchViewModel searchParams)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddApptCase);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchParams", searchParams);
            AddApptCaseOverride(callInfo, searchParams);
            return callInfo;
        }

        [NonAction]
        partial void InsertCaseOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.AddAppointmentCaseSearchViewModel searchParams);

        [NonAction]
        public override System.Web.Mvc.JsonResult InsertCase(LALoDep.Models.CaseOpening.AddAppointmentCaseSearchViewModel searchParams)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.InsertCase);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchParams", searchParams);
            InsertCaseOverride(callInfo, searchParams);
            return callInfo;
        }

        [NonAction]
        partial void HearingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Hearing(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Hearing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            HearingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void HearingSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.HearingModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult HearingSave(LALoDep.Models.CaseOpening.HearingModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.HearingSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            HearingSaveOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void HearingDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult HearingDelete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            HearingDeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void HearingUpdateOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.HearingModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult HearingUpdate(LALoDep.Models.CaseOpening.HearingModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.HearingUpdate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            HearingUpdateOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void LegalNumbersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LegalNumbers()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LegalNumbers);
            LegalNumbersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LegalNumberSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.LegalNumberModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult LegalNumberSave(LALoDep.Models.CaseOpening.LegalNumberModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LegalNumberSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            LegalNumberSaveOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void LegalPartiesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LegalParties()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LegalParties);
            LegalPartiesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LegalPartiesSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.LegalPartiesModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult LegalPartiesSave(LALoDep.Models.CaseOpening.LegalPartiesModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LegalPartiesSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            LegalPartiesSaveOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void NotesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Notes()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Notes);
            NotesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NoteSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.NotesModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult NoteSave(LALoDep.Models.CaseOpening.NotesModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NoteSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            NoteSaveOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PetitionListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PetitionList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionList);
            PetitionListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PetitionAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PetitionAdd()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionAdd);
            PetitionAddOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PetitionEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PetitionEdit(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PetitionEditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PetitionSaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.CaseOpening.PetitionAddEditModel model, LALoDep.Models.CaseOpening.PetitionAddEditModel oldModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult PetitionSave(LALoDep.Models.CaseOpening.PetitionAddEditModel model, LALoDep.Models.CaseOpening.PetitionAddEditModel oldModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "oldModel", oldModel);
            PetitionSaveOverride(callInfo, model, oldModel);
            return callInfo;
        }

        [NonAction]
        partial void PetitionDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PetitionDelete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PetitionDeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PetitionCopyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PetitionCopy(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionCopy);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PetitionCopyOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PetitionCopyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.CaseOpening.PetitionCopyModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult PetitionCopy(LALoDep.Models.CaseOpening.PetitionCopyModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PetitionCopy);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PetitionCopyOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditAllegationFindingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditAllegationFinding()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditAllegationFinding);
            EditAllegationFindingOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditAllegationFindingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.CaseOpening.EditAllegationFindingViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditAllegationFinding(LALoDep.Models.CaseOpening.EditAllegationFindingViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditAllegationFinding);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EditAllegationFindingOverride(callInfo, viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
