// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LALoDep.Controllers
{
    public partial class InquiryController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected InquiryController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintCalendarManagement()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCalendarManagement);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SearchMasterCalendar()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SearchMasterCalendar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintMasterCalendar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMasterCalendar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintWithPhysicalFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintWithPhysicalFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MyJcatsAttyDailyTime()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyJcatsAttyDailyTime);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MyCalendar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyCalendar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetHearingDataForTableView()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetHearingDataForTableView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintMyCalendar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMyCalendar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Leave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Leave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteLeave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteLeave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult HearingOfficerTransfer()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingOfficerTransfer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult MyCaseLoadV2()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.MyCaseLoadV2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintMyCaseload()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMyCaseload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintMyCaseloadV2()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMyCaseloadV2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult UpdateReferralCase()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateReferralCase);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult WritAppealNoticeDuesByAttorney()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WritAppealNoticeDuesByAttorney);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ToDoList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ToDoList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ToDoListSearch()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ToDoListSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintToDoList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintToDoList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ToDoAddEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ToDoAddEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadToDoFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadToDoFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransferCase()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransferCase);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ReportTree()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ReportTree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReportParameter()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportParameter);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Download()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Download);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public InquiryController Actions { get { return MVC.Inquiry; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Inquiry";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Inquiry";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CalendarManagement = "CalendarManagement";
            public readonly string PrintCalendarManagement = "PrintCalendarManagement";
            public readonly string CaseloadManagement = "CaseloadManagement";
            public readonly string EmployeeRoster = "EmployeeRoster";
            public readonly string MasterCalendar = "MasterCalendar";
            public readonly string SearchMasterCalendar = "SearchMasterCalendar";
            public readonly string PrintMasterCalendar = "PrintMasterCalendar";
            public readonly string PrintWithPhysicalFile = "PrintWithPhysicalFile";
            public readonly string MyJcatsAtty = "MyJcatsAtty";
            public readonly string MyJcatsAttyDailyTime = "MyJcatsAttyDailyTime";
            public readonly string MyCalendar = "MyCalendar";
            public readonly string GetHearingDataForTableView = "GetHearingDataForTableView";
            public readonly string PrintMyCalendar = "PrintMyCalendar";
            public readonly string Leave = "Leave";
            public readonly string DeleteLeave = "DeleteLeave";
            public readonly string HearingOfficerTransfer = "HearingOfficerTransfer";
            public readonly string MyCaseLoad = "MyCaseLoad";
            public readonly string MyCaseLoadV2 = "MyCaseLoadV2";
            public readonly string PrintMyCaseload = "PrintMyCaseload";
            public readonly string PrintMyCaseloadV2 = "PrintMyCaseloadV2";
            public readonly string MyJcatsInv = "MyJcatsInv";
            public readonly string MyJcatsMgmt = "MyJcatsMgmt";
            public readonly string ReferralEventCalendar = "ReferralEventCalendar";
            public readonly string UpdateReferralCase = "UpdateReferralCase";
            public readonly string SupvAtty = "SupvAtty";
            public readonly string WritAppealNoticeDuesByAttorney = "WritAppealNoticeDuesByAttorney";
            public readonly string ToDoList = "ToDoList";
            public readonly string ToDoListSearch = "ToDoListSearch";
            public readonly string PrintToDoList = "PrintToDoList";
            public readonly string ToDoAddEdit = "ToDoAddEdit";
            public readonly string DownloadToDoFile = "DownloadToDoFile";
            public readonly string TransferCase = "TransferCase";
            public readonly string Reports = "Reports";
            public readonly string ReportTree = "ReportTree";
            public readonly string ReportParameter = "ReportParameter";
            public readonly string ReportCaseloadSummary = "ReportCaseloadSummary";
            public readonly string ReportHearingSummary = "ReportHearingSummary";
            public readonly string ReportRFDCaseloadSummary = "ReportRFDCaseloadSummary";
            public readonly string Download = "Download";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CalendarManagement = "CalendarManagement";
            public const string PrintCalendarManagement = "PrintCalendarManagement";
            public const string CaseloadManagement = "CaseloadManagement";
            public const string EmployeeRoster = "EmployeeRoster";
            public const string MasterCalendar = "MasterCalendar";
            public const string SearchMasterCalendar = "SearchMasterCalendar";
            public const string PrintMasterCalendar = "PrintMasterCalendar";
            public const string PrintWithPhysicalFile = "PrintWithPhysicalFile";
            public const string MyJcatsAtty = "MyJcatsAtty";
            public const string MyJcatsAttyDailyTime = "MyJcatsAttyDailyTime";
            public const string MyCalendar = "MyCalendar";
            public const string GetHearingDataForTableView = "GetHearingDataForTableView";
            public const string PrintMyCalendar = "PrintMyCalendar";
            public const string Leave = "Leave";
            public const string DeleteLeave = "DeleteLeave";
            public const string HearingOfficerTransfer = "HearingOfficerTransfer";
            public const string MyCaseLoad = "MyCaseLoad";
            public const string MyCaseLoadV2 = "MyCaseLoadV2";
            public const string PrintMyCaseload = "PrintMyCaseload";
            public const string PrintMyCaseloadV2 = "PrintMyCaseloadV2";
            public const string MyJcatsInv = "MyJcatsInv";
            public const string MyJcatsMgmt = "MyJcatsMgmt";
            public const string ReferralEventCalendar = "ReferralEventCalendar";
            public const string UpdateReferralCase = "UpdateReferralCase";
            public const string SupvAtty = "SupvAtty";
            public const string WritAppealNoticeDuesByAttorney = "WritAppealNoticeDuesByAttorney";
            public const string ToDoList = "ToDoList";
            public const string ToDoListSearch = "ToDoListSearch";
            public const string PrintToDoList = "PrintToDoList";
            public const string ToDoAddEdit = "ToDoAddEdit";
            public const string DownloadToDoFile = "DownloadToDoFile";
            public const string TransferCase = "TransferCase";
            public const string Reports = "Reports";
            public const string ReportTree = "ReportTree";
            public const string ReportParameter = "ReportParameter";
            public const string ReportCaseloadSummary = "ReportCaseloadSummary";
            public const string ReportHearingSummary = "ReportHearingSummary";
            public const string ReportRFDCaseloadSummary = "ReportRFDCaseloadSummary";
            public const string Download = "Download";
        }


        static readonly ActionParamsClass_CalendarManagement s_params_CalendarManagement = new ActionParamsClass_CalendarManagement();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CalendarManagement CalendarManagementParams { get { return s_params_CalendarManagement; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CalendarManagement
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_PrintCalendarManagement s_params_PrintCalendarManagement = new ActionParamsClass_PrintCalendarManagement();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintCalendarManagement PrintCalendarManagementParams { get { return s_params_PrintCalendarManagement; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintCalendarManagement
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_CaseloadManagement s_params_CaseloadManagement = new ActionParamsClass_CaseloadManagement();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CaseloadManagement CaseloadManagementParams { get { return s_params_CaseloadManagement; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CaseloadManagement
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EmployeeRoster s_params_EmployeeRoster = new ActionParamsClass_EmployeeRoster();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EmployeeRoster EmployeeRosterParams { get { return s_params_EmployeeRoster; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EmployeeRoster
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_SearchMasterCalendar s_params_SearchMasterCalendar = new ActionParamsClass_SearchMasterCalendar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchMasterCalendar SearchMasterCalendarParams { get { return s_params_SearchMasterCalendar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchMasterCalendar
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_PrintMasterCalendar s_params_PrintMasterCalendar = new ActionParamsClass_PrintMasterCalendar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintMasterCalendar PrintMasterCalendarParams { get { return s_params_PrintMasterCalendar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintMasterCalendar
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_PrintWithPhysicalFile s_params_PrintWithPhysicalFile = new ActionParamsClass_PrintWithPhysicalFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintWithPhysicalFile PrintWithPhysicalFileParams { get { return s_params_PrintWithPhysicalFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintWithPhysicalFile
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_MyJcatsAtty s_params_MyJcatsAtty = new ActionParamsClass_MyJcatsAtty();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyJcatsAtty MyJcatsAttyParams { get { return s_params_MyJcatsAtty; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyJcatsAtty
        {
            public readonly string StartDate = "StartDate";
            public readonly string EndDate = "EndDate";
        }
        static readonly ActionParamsClass_MyJcatsAttyDailyTime s_params_MyJcatsAttyDailyTime = new ActionParamsClass_MyJcatsAttyDailyTime();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyJcatsAttyDailyTime MyJcatsAttyDailyTimeParams { get { return s_params_MyJcatsAttyDailyTime; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyJcatsAttyDailyTime
        {
            public readonly string StartDate = "StartDate";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_MyCalendar s_params_MyCalendar = new ActionParamsClass_MyCalendar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyCalendar MyCalendarParams { get { return s_params_MyCalendar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyCalendar
        {
            public readonly string p = "p";
        }
        static readonly ActionParamsClass_GetHearingDataForTableView s_params_GetHearingDataForTableView = new ActionParamsClass_GetHearingDataForTableView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetHearingDataForTableView GetHearingDataForTableViewParams { get { return s_params_GetHearingDataForTableView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetHearingDataForTableView
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_PrintMyCalendar s_params_PrintMyCalendar = new ActionParamsClass_PrintMyCalendar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintMyCalendar PrintMyCalendarParams { get { return s_params_PrintMyCalendar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintMyCalendar
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Leave s_params_Leave = new ActionParamsClass_Leave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Leave LeaveParams { get { return s_params_Leave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Leave
        {
            public readonly string id = "id";
            public readonly string p = "p";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_DeleteLeave s_params_DeleteLeave = new ActionParamsClass_DeleteLeave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteLeave DeleteLeaveParams { get { return s_params_DeleteLeave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteLeave
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_HearingOfficerTransfer s_params_HearingOfficerTransfer = new ActionParamsClass_HearingOfficerTransfer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HearingOfficerTransfer HearingOfficerTransferParams { get { return s_params_HearingOfficerTransfer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HearingOfficerTransfer
        {
            public readonly string p = "p";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_MyCaseLoad s_params_MyCaseLoad = new ActionParamsClass_MyCaseLoad();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyCaseLoad MyCaseLoadParams { get { return s_params_MyCaseLoad; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyCaseLoad
        {
            public readonly string id = "id";
            public readonly string ClientNameLast = "ClientNameLast";
            public readonly string ClientNameFirst = "ClientNameFirst";
            public readonly string CaseNumber = "CaseNumber";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_MyCaseLoadV2 s_params_MyCaseLoadV2 = new ActionParamsClass_MyCaseLoadV2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyCaseLoadV2 MyCaseLoadV2Params { get { return s_params_MyCaseLoadV2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyCaseLoadV2
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_PrintMyCaseload s_params_PrintMyCaseload = new ActionParamsClass_PrintMyCaseload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintMyCaseload PrintMyCaseloadParams { get { return s_params_PrintMyCaseload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintMyCaseload
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_PrintMyCaseloadV2 s_params_PrintMyCaseloadV2 = new ActionParamsClass_PrintMyCaseloadV2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintMyCaseloadV2 PrintMyCaseloadV2Params { get { return s_params_PrintMyCaseloadV2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintMyCaseloadV2
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_MyJcatsInv s_params_MyJcatsInv = new ActionParamsClass_MyJcatsInv();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyJcatsInv MyJcatsInvParams { get { return s_params_MyJcatsInv; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyJcatsInv
        {
            public readonly string StartDate = "StartDate";
            public readonly string EndDate = "EndDate";
        }
        static readonly ActionParamsClass_MyJcatsMgmt s_params_MyJcatsMgmt = new ActionParamsClass_MyJcatsMgmt();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyJcatsMgmt MyJcatsMgmtParams { get { return s_params_MyJcatsMgmt; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyJcatsMgmt
        {
            public readonly string StartDate = "StartDate";
            public readonly string EndDate = "EndDate";
        }
        static readonly ActionParamsClass_ReferralEventCalendar s_params_ReferralEventCalendar = new ActionParamsClass_ReferralEventCalendar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReferralEventCalendar ReferralEventCalendarParams { get { return s_params_ReferralEventCalendar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReferralEventCalendar
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_UpdateReferralCase s_params_UpdateReferralCase = new ActionParamsClass_UpdateReferralCase();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateReferralCase UpdateReferralCaseParams { get { return s_params_UpdateReferralCase; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateReferralCase
        {
            public readonly string refID = "refID";
            public readonly string caseID = "caseID";
            public readonly string evtID = "evtID";
        }
        static readonly ActionParamsClass_SupvAtty s_params_SupvAtty = new ActionParamsClass_SupvAtty();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SupvAtty SupvAttyParams { get { return s_params_SupvAtty; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SupvAtty
        {
            public readonly string StartDate = "StartDate";
            public readonly string EndDate = "EndDate";
        }
        static readonly ActionParamsClass_WritAppealNoticeDuesByAttorney s_params_WritAppealNoticeDuesByAttorney = new ActionParamsClass_WritAppealNoticeDuesByAttorney();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WritAppealNoticeDuesByAttorney WritAppealNoticeDuesByAttorneyParams { get { return s_params_WritAppealNoticeDuesByAttorney; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WritAppealNoticeDuesByAttorney
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ToDoList s_params_ToDoList = new ActionParamsClass_ToDoList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ToDoList ToDoListParams { get { return s_params_ToDoList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ToDoList
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ToDoListSearch s_params_ToDoListSearch = new ActionParamsClass_ToDoListSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ToDoListSearch ToDoListSearchParams { get { return s_params_ToDoListSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ToDoListSearch
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_PrintToDoList s_params_PrintToDoList = new ActionParamsClass_PrintToDoList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintToDoList PrintToDoListParams { get { return s_params_PrintToDoList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintToDoList
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ToDoAddEdit s_params_ToDoAddEdit = new ActionParamsClass_ToDoAddEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ToDoAddEdit ToDoAddEditParams { get { return s_params_ToDoAddEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ToDoAddEdit
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_DownloadToDoFile s_params_DownloadToDoFile = new ActionParamsClass_DownloadToDoFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadToDoFile DownloadToDoFileParams { get { return s_params_DownloadToDoFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadToDoFile
        {
            public readonly string name = "name";
            public readonly string path = "path";
        }
        static readonly ActionParamsClass_TransferCase s_params_TransferCase = new ActionParamsClass_TransferCase();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransferCase TransferCaseParams { get { return s_params_TransferCase; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransferCase
        {
            public readonly string id = "id";
            public readonly string pId = "pId";
            public readonly string roleTypeId = "roleTypeId";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ReportTree s_params_ReportTree = new ActionParamsClass_ReportTree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportTree ReportTreeParams { get { return s_params_ReportTree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportTree
        {
            public readonly string ReportID = "ReportID";
        }
        static readonly ActionParamsClass_ReportParameter s_params_ReportParameter = new ActionParamsClass_ReportParameter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportParameter ReportParameterParams { get { return s_params_ReportParameter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportParameter
        {
            public readonly string ID = "ID";
            public readonly string PageID = "PageID";
            public readonly string reportParametersViewModel = "reportParametersViewModel";
        }
        static readonly ActionParamsClass_ReportCaseloadSummary s_params_ReportCaseloadSummary = new ActionParamsClass_ReportCaseloadSummary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportCaseloadSummary ReportCaseloadSummaryParams { get { return s_params_ReportCaseloadSummary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportCaseloadSummary
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ReportHearingSummary s_params_ReportHearingSummary = new ActionParamsClass_ReportHearingSummary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportHearingSummary ReportHearingSummaryParams { get { return s_params_ReportHearingSummary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportHearingSummary
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ReportRFDCaseloadSummary s_params_ReportRFDCaseloadSummary = new ActionParamsClass_ReportRFDCaseloadSummary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReportRFDCaseloadSummary ReportRFDCaseloadSummaryParams { get { return s_params_ReportRFDCaseloadSummary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReportRFDCaseloadSummary
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_Download s_params_Download = new ActionParamsClass_Download();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Download DownloadParams { get { return s_params_Download; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Download
        {
            public readonly string file = "file";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _calendarSearchResult = "_calendarSearchResult";
                public readonly string _caseloadSearchresult = "_caseloadSearchresult";
                public readonly string _myCaseLoadSearchResult = "_myCaseLoadSearchResult";
                public readonly string _myCaseLoadV2SearchResult = "_myCaseLoadV2SearchResult";
                public readonly string _myJcatsAttyDailyTimePartial = "_myJcatsAttyDailyTimePartial";
                public readonly string _referralEventCalendarPartial = "_referralEventCalendarPartial";
                public readonly string CalendarManagement = "CalendarManagement";
                public readonly string CaseloadManagement = "CaseloadManagement";
                public readonly string EmployeeRoster = "EmployeeRoster";
                public readonly string HearingOfficerTransfer = "HearingOfficerTransfer";
                public readonly string Leave = "Leave";
                public readonly string MasterCalendar = "MasterCalendar";
                public readonly string MyCalendar = "MyCalendar";
                public readonly string MyCaseLoad = "MyCaseLoad";
                public readonly string MyCaseLoadV2 = "MyCaseLoadV2";
                public readonly string MyJcatsAtty = "MyJcatsAtty";
                public readonly string MyJcatsInv = "MyJcatsInv";
                public readonly string MyJcatsMgmt = "MyJcatsMgmt";
                public readonly string ReferralEventCalendar = "ReferralEventCalendar";
                public readonly string ReportCaseloadSummary = "ReportCaseloadSummary";
                public readonly string ReportHearingSummary = "ReportHearingSummary";
                public readonly string ReportParameter = "ReportParameter";
                public readonly string ReportRFDCaseloadSummary = "ReportRFDCaseloadSummary";
                public readonly string Reports = "Reports";
                public readonly string SupvAtty = "SupvAtty";
                public readonly string ToDoAddEdit = "ToDoAddEdit";
                public readonly string ToDoList = "ToDoList";
                public readonly string TransferCase = "TransferCase";
                public readonly string WritAppealNoticeDuesByAttorney = "WritAppealNoticeDuesByAttorney";
            }
            public readonly string _calendarSearchResult = "~/Views/Inquiry/_calendarSearchResult.cshtml";
            public readonly string _caseloadSearchresult = "~/Views/Inquiry/_caseloadSearchresult.cshtml";
            public readonly string _myCaseLoadSearchResult = "~/Views/Inquiry/_myCaseLoadSearchResult.cshtml";
            public readonly string _myCaseLoadV2SearchResult = "~/Views/Inquiry/_myCaseLoadV2SearchResult.cshtml";
            public readonly string _myJcatsAttyDailyTimePartial = "~/Views/Inquiry/_myJcatsAttyDailyTimePartial.cshtml";
            public readonly string _referralEventCalendarPartial = "~/Views/Inquiry/_referralEventCalendarPartial.cshtml";
            public readonly string CalendarManagement = "~/Views/Inquiry/CalendarManagement.cshtml";
            public readonly string CaseloadManagement = "~/Views/Inquiry/CaseloadManagement.cshtml";
            public readonly string EmployeeRoster = "~/Views/Inquiry/EmployeeRoster.cshtml";
            public readonly string HearingOfficerTransfer = "~/Views/Inquiry/HearingOfficerTransfer.cshtml";
            public readonly string Leave = "~/Views/Inquiry/Leave.cshtml";
            public readonly string MasterCalendar = "~/Views/Inquiry/MasterCalendar.cshtml";
            public readonly string MyCalendar = "~/Views/Inquiry/MyCalendar.cshtml";
            public readonly string MyCaseLoad = "~/Views/Inquiry/MyCaseLoad.cshtml";
            public readonly string MyCaseLoadV2 = "~/Views/Inquiry/MyCaseLoadV2.cshtml";
            public readonly string MyJcatsAtty = "~/Views/Inquiry/MyJcatsAtty.cshtml";
            public readonly string MyJcatsInv = "~/Views/Inquiry/MyJcatsInv.cshtml";
            public readonly string MyJcatsMgmt = "~/Views/Inquiry/MyJcatsMgmt.cshtml";
            public readonly string ReferralEventCalendar = "~/Views/Inquiry/ReferralEventCalendar.cshtml";
            public readonly string ReportCaseloadSummary = "~/Views/Inquiry/ReportCaseloadSummary.cshtml";
            public readonly string ReportHearingSummary = "~/Views/Inquiry/ReportHearingSummary.cshtml";
            public readonly string ReportParameter = "~/Views/Inquiry/ReportParameter.cshtml";
            public readonly string ReportRFDCaseloadSummary = "~/Views/Inquiry/ReportRFDCaseloadSummary.cshtml";
            public readonly string Reports = "~/Views/Inquiry/Reports.cshtml";
            public readonly string SupvAtty = "~/Views/Inquiry/SupvAtty.cshtml";
            public readonly string ToDoAddEdit = "~/Views/Inquiry/ToDoAddEdit.cshtml";
            public readonly string ToDoList = "~/Views/Inquiry/ToDoList.cshtml";
            public readonly string TransferCase = "~/Views/Inquiry/TransferCase.cshtml";
            public readonly string WritAppealNoticeDuesByAttorney = "~/Views/Inquiry/WritAppealNoticeDuesByAttorney.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_InquiryController : LALoDep.Controllers.InquiryController
    {
        public T4MVC_InquiryController() : base(Dummy.Instance) { }

        [NonAction]
        partial void CalendarManagementOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CalendarManagement()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CalendarManagement);
            CalendarManagementOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CalendarManagementOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, LALoDep.Models.Inquiry.CalendarManagementViewModel model);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult CalendarManagement(LALoDep.Models.Inquiry.CalendarManagementViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.CalendarManagement);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CalendarManagementOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PrintCalendarManagementOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.CalendarManagementViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintCalendarManagement(LALoDep.Models.Inquiry.CalendarManagementViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintCalendarManagement);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            PrintCalendarManagementOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void CaseloadManagementOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CaseloadManagement()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseloadManagement);
            CaseloadManagementOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CaseloadManagementOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, LALoDep.Models.Inquiry.CaseLoadManagementViewModel model);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult CaseloadManagement(LALoDep.Models.Inquiry.CaseLoadManagementViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.CaseloadManagement);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CaseloadManagementOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EmployeeRosterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EmployeeRoster()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EmployeeRoster);
            EmployeeRosterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EmployeeRosterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.EmployeeRosterViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult EmployeeRoster(LALoDep.Models.EmployeeRosterViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EmployeeRoster);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EmployeeRosterOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void MasterCalendarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MasterCalendar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MasterCalendar);
            MasterCalendarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SearchMasterCalendarOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Inquiry.MasterCalendarViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult SearchMasterCalendar(LALoDep.Models.Inquiry.MasterCalendarViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SearchMasterCalendar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            SearchMasterCalendarOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void PrintMasterCalendarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.MasterCalendarViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintMasterCalendar(LALoDep.Models.Inquiry.MasterCalendarViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMasterCalendar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            PrintMasterCalendarOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void PrintWithPhysicalFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.MasterCalendarViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintWithPhysicalFile(LALoDep.Models.Inquiry.MasterCalendarViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintWithPhysicalFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            PrintWithPhysicalFileOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void MyJcatsAttyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyJcatsAtty()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyJcatsAtty);
            MyJcatsAttyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MyJcatsAttyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime StartDate, System.DateTime EndDate);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyJcatsAtty(System.DateTime StartDate, System.DateTime EndDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyJcatsAtty);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "StartDate", StartDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "EndDate", EndDate);
            MyJcatsAttyOverride(callInfo, StartDate, EndDate);
            return callInfo;
        }

        [NonAction]
        partial void MyJcatsAttyDailyTimeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string StartDate, string page);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyJcatsAttyDailyTime(string StartDate, string page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyJcatsAttyDailyTime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "StartDate", StartDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            MyJcatsAttyDailyTimeOverride(callInfo, StartDate, page);
            return callInfo;
        }

        [NonAction]
        partial void MyCalendarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string p);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyCalendar(string p)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyCalendar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "p", p);
            MyCalendarOverride(callInfo, p);
            return callInfo;
        }

        [NonAction]
        partial void GetHearingDataForTableViewOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Jcats.SD.UI.ViewModels.MyCalendarModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetHearingDataForTableView(Jcats.SD.UI.ViewModels.MyCalendarModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetHearingDataForTableView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            GetHearingDataForTableViewOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PrintMyCalendarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Jcats.SD.UI.ViewModels.MyCalendarModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintMyCalendar(Jcats.SD.UI.ViewModels.MyCalendarModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMyCalendar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PrintMyCalendarOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void LeaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string p);

        [NonAction]
        public override System.Web.Mvc.ActionResult Leave(string id, string p)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Leave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "p", p);
            LeaveOverride(callInfo, id, p);
            return callInfo;
        }

        [NonAction]
        partial void LeaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.LeaveViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult Leave(LALoDep.Models.Inquiry.LeaveViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Leave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            LeaveOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void DeleteLeaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteLeave(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteLeave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteLeaveOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void HearingOfficerTransferOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string p);

        [NonAction]
        public override System.Web.Mvc.ActionResult HearingOfficerTransfer(string p)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingOfficerTransfer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "p", p);
            HearingOfficerTransferOverride(callInfo, p);
            return callInfo;
        }

        [NonAction]
        partial void HearingOfficerTransferOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Inquiry.JudgeTransferViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult HearingOfficerTransfer(LALoDep.Models.Inquiry.JudgeTransferViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.HearingOfficerTransfer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            HearingOfficerTransferOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void MyCaseLoadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string ClientNameLast, string ClientNameFirst, string CaseNumber);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyCaseLoad(string id, string ClientNameLast, string ClientNameFirst, string CaseNumber)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyCaseLoad);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ClientNameLast", ClientNameLast);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ClientNameFirst", ClientNameFirst);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CaseNumber", CaseNumber);
            MyCaseLoadOverride(callInfo, id, ClientNameLast, ClientNameFirst, CaseNumber);
            return callInfo;
        }

        [NonAction]
        partial void MyCaseLoadOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, LALoDep.Models.Inquiry.MyCaseLoadIndexViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult MyCaseLoad(LALoDep.Models.Inquiry.MyCaseLoadIndexViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.MyCaseLoad);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            MyCaseLoadOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void MyCaseLoadV2Override(T4MVC_System_Web_Mvc_PartialViewResult callInfo, LALoDep.Models.Inquiry.MyCaseLoadIndexViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult MyCaseLoadV2(LALoDep.Models.Inquiry.MyCaseLoadIndexViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.MyCaseLoadV2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            MyCaseLoadV2Override(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void PrintMyCaseloadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.MyCaseLoadIndexViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintMyCaseload(LALoDep.Models.Inquiry.MyCaseLoadIndexViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMyCaseload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            PrintMyCaseloadOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void PrintMyCaseloadV2Override(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.MyCaseLoadIndexViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintMyCaseloadV2(LALoDep.Models.Inquiry.MyCaseLoadIndexViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMyCaseloadV2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            PrintMyCaseloadV2Override(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void MyJcatsInvOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyJcatsInv()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyJcatsInv);
            MyJcatsInvOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MyJcatsInvOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime? StartDate, System.DateTime? EndDate);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyJcatsInv(System.DateTime? StartDate, System.DateTime? EndDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyJcatsInv);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "StartDate", StartDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "EndDate", EndDate);
            MyJcatsInvOverride(callInfo, StartDate, EndDate);
            return callInfo;
        }

        [NonAction]
        partial void MyJcatsMgmtOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyJcatsMgmt()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyJcatsMgmt);
            MyJcatsMgmtOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MyJcatsMgmtOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime StartDate, System.DateTime EndDate);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyJcatsMgmt(System.DateTime StartDate, System.DateTime EndDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyJcatsMgmt);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "StartDate", StartDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "EndDate", EndDate);
            MyJcatsMgmtOverride(callInfo, StartDate, EndDate);
            return callInfo;
        }

        [NonAction]
        partial void ReferralEventCalendarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReferralEventCalendar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReferralEventCalendar);
            ReferralEventCalendarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReferralEventCalendarOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, LALoDep.Models.Inquiry.ReferralEventCalendarViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ReferralEventCalendar(LALoDep.Models.Inquiry.ReferralEventCalendarViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ReferralEventCalendar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ReferralEventCalendarOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void UpdateReferralCaseOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int? refID, int? caseID, int? evtID);

        [NonAction]
        public override System.Web.Mvc.JsonResult UpdateReferralCase(int? refID, int? caseID, int? evtID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateReferralCase);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "refID", refID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "caseID", caseID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "evtID", evtID);
            UpdateReferralCaseOverride(callInfo, refID, caseID, evtID);
            return callInfo;
        }

        [NonAction]
        partial void SupvAttyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SupvAtty()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SupvAtty);
            SupvAttyOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SupvAttyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime StartDate, System.DateTime EndDate);

        [NonAction]
        public override System.Web.Mvc.ActionResult SupvAtty(System.DateTime StartDate, System.DateTime EndDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SupvAtty);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "StartDate", StartDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "EndDate", EndDate);
            SupvAttyOverride(callInfo, StartDate, EndDate);
            return callInfo;
        }

        [NonAction]
        partial void WritAppealNoticeDuesByAttorneyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult WritAppealNoticeDuesByAttorney(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WritAppealNoticeDuesByAttorney);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            WritAppealNoticeDuesByAttorneyOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ToDoListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ToDoList(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ToDoList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ToDoListOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ToDoListSearchOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.ToDoListViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult ToDoListSearch(LALoDep.Models.ToDoListViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ToDoListSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ToDoListSearchOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void PrintToDoListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.ToDoListViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintToDoList(LALoDep.Models.ToDoListViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintToDoList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            PrintToDoListOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void ToDoAddEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ToDoAddEdit(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ToDoAddEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ToDoAddEditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ToDoAddEditOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.ToDoAddEditViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult ToDoAddEdit(LALoDep.Models.ToDoAddEditViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ToDoAddEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ToDoAddEditOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void DownloadToDoFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string name, string path);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadToDoFile(string name, string path)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadToDoFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "path", path);
            DownloadToDoFileOverride(callInfo, name, path);
            return callInfo;
        }

        [NonAction]
        partial void TransferCaseOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string pId, string roleTypeId);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransferCase(string id, string pId, string roleTypeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransferCase);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pId", pId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "roleTypeId", roleTypeId);
            TransferCaseOverride(callInfo, id, pId, roleTypeId);
            return callInfo;
        }

        [NonAction]
        partial void TransferCaseOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.TransferCaseViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransferCase(LALoDep.Models.Inquiry.TransferCaseViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransferCase);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            TransferCaseOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void ReportsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Reports()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reports);
            ReportsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReportTreeOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int ReportID);

        [NonAction]
        public override System.Web.Mvc.JsonResult ReportTree(int ReportID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ReportTree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ReportID", ReportID);
            ReportTreeOverride(callInfo, ReportID);
            return callInfo;
        }

        [NonAction]
        partial void ReportParameterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ID, string PageID);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportParameter(string ID, string PageID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportParameter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ID", ID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "PageID", PageID);
            ReportParameterOverride(callInfo, ID, PageID);
            return callInfo;
        }

        [NonAction]
        partial void ReportParameterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.ReportParametersViewModel reportParametersViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportParameter(LALoDep.Models.Inquiry.ReportParametersViewModel reportParametersViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportParameter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "reportParametersViewModel", reportParametersViewModel);
            ReportParameterOverride(callInfo, reportParametersViewModel);
            return callInfo;
        }

        [NonAction]
        partial void ReportCaseloadSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportCaseloadSummary()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportCaseloadSummary);
            ReportCaseloadSummaryOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReportCaseloadSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.ReportCaseloadSummaryViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportCaseloadSummary(LALoDep.Models.Inquiry.ReportCaseloadSummaryViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportCaseloadSummary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ReportCaseloadSummaryOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void ReportHearingSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportHearingSummary()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportHearingSummary);
            ReportHearingSummaryOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReportHearingSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.ReportHearingSummaryViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportHearingSummary(LALoDep.Models.Inquiry.ReportHearingSummaryViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportHearingSummary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ReportHearingSummaryOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void ReportRFDCaseloadSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportRFDCaseloadSummary()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportRFDCaseloadSummary);
            ReportRFDCaseloadSummaryOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReportRFDCaseloadSummaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Inquiry.ReportRFDCaseloadSummaryViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReportRFDCaseloadSummary(LALoDep.Models.Inquiry.ReportRFDCaseloadSummaryViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReportRFDCaseloadSummary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ReportRFDCaseloadSummaryOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void DownloadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string file);

        [NonAction]
        public override System.Web.Mvc.ActionResult Download(string file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Download);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            DownloadOverride(callInfo, file);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
