// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LALoDep.Controllers.Inquiry
{
    public partial class InvoiceController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected InvoiceController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InvoiceNote()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceNote);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditHearingAmount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditHearingAmount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InvoiceSentPopup()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceSentPopup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InvoiceDelete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InvoiceVoid()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceVoid);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RegenerateInvoice()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RegenerateInvoice);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public InvoiceController Actions { get { return MVC.Invoice; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Invoice";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Invoice";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Search = "Search";
            public readonly string InvoiceNote = "InvoiceNote";
            public readonly string EditHearingAmount = "EditHearingAmount";
            public readonly string InvoiceSentPopup = "InvoiceSentPopup";
            public readonly string InvoiceDelete = "InvoiceDelete";
            public readonly string InvoiceVoid = "InvoiceVoid";
            public readonly string RegenerateInvoice = "RegenerateInvoice";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Search = "Search";
            public const string InvoiceNote = "InvoiceNote";
            public const string EditHearingAmount = "EditHearingAmount";
            public const string InvoiceSentPopup = "InvoiceSentPopup";
            public const string InvoiceDelete = "InvoiceDelete";
            public const string InvoiceVoid = "InvoiceVoid";
            public const string RegenerateInvoice = "RegenerateInvoice";
        }


        static readonly ActionParamsClass_InvoiceNote s_params_InvoiceNote = new ActionParamsClass_InvoiceNote();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InvoiceNote InvoiceNoteParams { get { return s_params_InvoiceNote; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InvoiceNote
        {
            public readonly string id = "id";
            public readonly string pkId = "pkId";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_EditHearingAmount s_params_EditHearingAmount = new ActionParamsClass_EditHearingAmount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditHearingAmount EditHearingAmountParams { get { return s_params_EditHearingAmount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditHearingAmount
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_InvoiceSentPopup s_params_InvoiceSentPopup = new ActionParamsClass_InvoiceSentPopup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InvoiceSentPopup InvoiceSentPopupParams { get { return s_params_InvoiceSentPopup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InvoiceSentPopup
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_InvoiceDelete s_params_InvoiceDelete = new ActionParamsClass_InvoiceDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InvoiceDelete InvoiceDeleteParams { get { return s_params_InvoiceDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InvoiceDelete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_InvoiceVoid s_params_InvoiceVoid = new ActionParamsClass_InvoiceVoid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InvoiceVoid InvoiceVoidParams { get { return s_params_InvoiceVoid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InvoiceVoid
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RegenerateInvoice s_params_RegenerateInvoice = new ActionParamsClass_RegenerateInvoice();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RegenerateInvoice RegenerateInvoiceParams { get { return s_params_RegenerateInvoice; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RegenerateInvoice
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string EditHearingAmount = "EditHearingAmount";
                public readonly string InvoiceNote = "InvoiceNote";
                public readonly string InvoiceSentPopup = "InvoiceSentPopup";
                public readonly string Search = "Search";
            }
            public readonly string EditHearingAmount = "~/Views/Invoice/EditHearingAmount.cshtml";
            public readonly string InvoiceNote = "~/Views/Invoice/InvoiceNote.cshtml";
            public readonly string InvoiceSentPopup = "~/Views/Invoice/InvoiceSentPopup.cshtml";
            public readonly string Search = "~/Views/Invoice/Search.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_InvoiceController : LALoDep.Controllers.Inquiry.InvoiceController
    {
        public T4MVC_InvoiceController() : base(Dummy.Instance) { }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            SearchOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceNoteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string pkId);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceNote(string id, string pkId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceNote);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pkId", pkId);
            InvoiceNoteOverride(callInfo, id, pkId);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceNoteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.SaveNoteViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceNote(LALoDep.Models.SaveNoteViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceNote);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            InvoiceNoteOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void EditHearingAmountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditHearingAmount(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditHearingAmount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditHearingAmountOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditHearingAmountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.EditHearingAmountViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditHearingAmount(LALoDep.Models.EditHearingAmountViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditHearingAmount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EditHearingAmountOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceSentPopupOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceSentPopup(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceSentPopup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            InvoiceSentPopupOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceDelete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            InvoiceDeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceVoidOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceVoid(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceVoid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            InvoiceVoidOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RegenerateInvoiceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult RegenerateInvoice(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RegenerateInvoice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RegenerateInvoiceOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
