// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LALoDep.Controllers
{
    public partial class MailController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MailController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MailController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual ActionMailer.Net.Mvc.EmailResult ResetPassword()
        {
            return new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.ResetPassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual ActionMailer.Net.Mvc.EmailResult RaiseElmahErrorEmail()
        {
            return new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.RaiseElmahErrorEmail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual ActionMailer.Net.Mvc.EmailResult ClearConsernEmailNotification()
        {
            return new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.ClearConsernEmailNotification);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual ActionMailer.Net.Mvc.EmailResult TwilioReplyEmailNotification()
        {
            return new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.TwilioReplyEmailNotification);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual ActionMailer.Net.Mvc.EmailResult Email()
        {
            return new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.Email);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MailController Actions { get { return MVC.Mail; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Mail";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Mail";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ResetPassword = "ResetPassword";
            public readonly string RaiseElmahErrorEmail = "RaiseElmahErrorEmail";
            public readonly string ClearConsernEmailNotification = "ClearConsernEmailNotification";
            public readonly string TwilioReplyEmailNotification = "TwilioReplyEmailNotification";
            public readonly string Email = "Email";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ResetPassword = "ResetPassword";
            public const string RaiseElmahErrorEmail = "RaiseElmahErrorEmail";
            public const string ClearConsernEmailNotification = "ClearConsernEmailNotification";
            public const string TwilioReplyEmailNotification = "TwilioReplyEmailNotification";
            public const string Email = "Email";
        }


        static readonly ActionParamsClass_ResetPassword s_params_ResetPassword = new ActionParamsClass_ResetPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPassword ResetPasswordParams { get { return s_params_ResetPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPassword
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_RaiseElmahErrorEmail s_params_RaiseElmahErrorEmail = new ActionParamsClass_RaiseElmahErrorEmail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RaiseElmahErrorEmail RaiseElmahErrorEmailParams { get { return s_params_RaiseElmahErrorEmail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RaiseElmahErrorEmail
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ClearConsernEmailNotification s_params_ClearConsernEmailNotification = new ActionParamsClass_ClearConsernEmailNotification();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClearConsernEmailNotification ClearConsernEmailNotificationParams { get { return s_params_ClearConsernEmailNotification; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClearConsernEmailNotification
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_TwilioReplyEmailNotification s_params_TwilioReplyEmailNotification = new ActionParamsClass_TwilioReplyEmailNotification();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TwilioReplyEmailNotification TwilioReplyEmailNotificationParams { get { return s_params_TwilioReplyEmailNotification; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TwilioReplyEmailNotification
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Email s_params_Email = new ActionParamsClass_Email();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Email EmailParams { get { return s_params_Email; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Email
        {
            public readonly string viewName = "viewName";
            public readonly string model = "model";
            public readonly string masterName = "masterName";
            public readonly string trimBody = "trimBody";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ClearConsernEmailNotification_html = "ClearConsernEmailNotification.html";
                public readonly string RaiseElmahErrorEmail_html = "RaiseElmahErrorEmail.html";
                public readonly string ResetPassword_html = "ResetPassword.html";
            }
            public readonly string ClearConsernEmailNotification_html = "~/Views/Mail/ClearConsernEmailNotification.html.cshtml";
            public readonly string RaiseElmahErrorEmail_html = "~/Views/Mail/RaiseElmahErrorEmail.html.cshtml";
            public readonly string ResetPassword_html = "~/Views/Mail/ResetPassword.html.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MailController : LALoDep.Controllers.MailController
    {
        public T4MVC_MailController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ResetPasswordOverride(T4MVC_ActionMailer_Net_Mvc_EmailResult callInfo, LALoDep.Models.EmailRecipient model);

        [NonAction]
        public override ActionMailer.Net.Mvc.EmailResult ResetPassword(LALoDep.Models.EmailRecipient model)
        {
            var callInfo = new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.ResetPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ResetPasswordOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void RaiseElmahErrorEmailOverride(T4MVC_ActionMailer_Net_Mvc_EmailResult callInfo, LALoDep.Models.EmailRecipient model);

        [NonAction]
        public override ActionMailer.Net.Mvc.EmailResult RaiseElmahErrorEmail(LALoDep.Models.EmailRecipient model)
        {
            var callInfo = new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.RaiseElmahErrorEmail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            RaiseElmahErrorEmailOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ClearConsernEmailNotificationOverride(T4MVC_ActionMailer_Net_Mvc_EmailResult callInfo, LALoDep.Models.EmailRecipient model);

        [NonAction]
        public override ActionMailer.Net.Mvc.EmailResult ClearConsernEmailNotification(LALoDep.Models.EmailRecipient model)
        {
            var callInfo = new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.ClearConsernEmailNotification);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ClearConsernEmailNotificationOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void TwilioReplyEmailNotificationOverride(T4MVC_ActionMailer_Net_Mvc_EmailResult callInfo, LALoDep.Models.EmailRecipient model);

        [NonAction]
        public override ActionMailer.Net.Mvc.EmailResult TwilioReplyEmailNotification(LALoDep.Models.EmailRecipient model)
        {
            var callInfo = new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.TwilioReplyEmailNotification);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            TwilioReplyEmailNotificationOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EmailOverride(T4MVC_ActionMailer_Net_Mvc_EmailResult callInfo, string viewName, object model, string masterName, bool trimBody);

        [NonAction]
        public override ActionMailer.Net.Mvc.EmailResult Email(string viewName, object model, string masterName, bool trimBody)
        {
            var callInfo = new T4MVC_ActionMailer_Net_Mvc_EmailResult(Area, Name, ActionNames.Email);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "masterName", masterName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "trimBody", trimBody);
            EmailOverride(callInfo, viewName, model, masterName, trimBody);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
