// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LALoDep.Areas.Mobile.Controllers
{
    public partial class CaseController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CaseController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CaseInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult HearingEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RecordTimeEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RecordTimeEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RecordTimeEditSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RecordTimeEditSave);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CaseController Actions { get { return MVC.Mobile.Case; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Mobile";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Case";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Case";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Search = "Search";
            public readonly string CaseInfo = "CaseInfo";
            public readonly string CaseAdd = "CaseAdd";
            public readonly string HearingAdd = "HearingAdd";
            public readonly string HearingEdit = "HearingEdit";
            public readonly string RecordTime = "RecordTime";
            public readonly string RecordTimeAdd = "RecordTimeAdd";
            public readonly string RecordTimeEdit = "RecordTimeEdit";
            public readonly string RecordTimeEditSave = "RecordTimeEditSave";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Search = "Search";
            public const string CaseInfo = "CaseInfo";
            public const string CaseAdd = "CaseAdd";
            public const string HearingAdd = "HearingAdd";
            public const string HearingEdit = "HearingEdit";
            public const string RecordTime = "RecordTime";
            public const string RecordTimeAdd = "RecordTimeAdd";
            public const string RecordTimeEdit = "RecordTimeEdit";
            public const string RecordTimeEditSave = "RecordTimeEditSave";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string searchParams = "searchParams";
        }
        static readonly ActionParamsClass_CaseInfo s_params_CaseInfo = new ActionParamsClass_CaseInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CaseInfo CaseInfoParams { get { return s_params_CaseInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CaseInfo
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CaseAdd s_params_CaseAdd = new ActionParamsClass_CaseAdd();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CaseAdd CaseAddParams { get { return s_params_CaseAdd; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CaseAdd
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_HearingAdd s_params_HearingAdd = new ActionParamsClass_HearingAdd();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HearingAdd HearingAddParams { get { return s_params_HearingAdd; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HearingAdd
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_HearingEdit s_params_HearingEdit = new ActionParamsClass_HearingEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HearingEdit HearingEditParams { get { return s_params_HearingEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HearingEdit
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_RecordTimeAdd s_params_RecordTimeAdd = new ActionParamsClass_RecordTimeAdd();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RecordTimeAdd RecordTimeAddParams { get { return s_params_RecordTimeAdd; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RecordTimeAdd
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_RecordTimeEdit s_params_RecordTimeEdit = new ActionParamsClass_RecordTimeEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RecordTimeEdit RecordTimeEditParams { get { return s_params_RecordTimeEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RecordTimeEdit
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RecordTimeEditSave s_params_RecordTimeEditSave = new ActionParamsClass_RecordTimeEditSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RecordTimeEditSave RecordTimeEditSaveParams { get { return s_params_RecordTimeEditSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RecordTimeEditSave
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CaseAdd = "CaseAdd";
                public readonly string CaseInfo = "CaseInfo";
                public readonly string HearingAdd = "HearingAdd";
                public readonly string HearingEdit = "HearingEdit";
                public readonly string RecordTime = "RecordTime";
                public readonly string RecordTimeAdd = "RecordTimeAdd";
                public readonly string RecordTimeEdit = "RecordTimeEdit";
                public readonly string Search = "Search";
            }
            public readonly string CaseAdd = "~/Areas/Mobile/Views/Case/CaseAdd.cshtml";
            public readonly string CaseInfo = "~/Areas/Mobile/Views/Case/CaseInfo.cshtml";
            public readonly string HearingAdd = "~/Areas/Mobile/Views/Case/HearingAdd.cshtml";
            public readonly string HearingEdit = "~/Areas/Mobile/Views/Case/HearingEdit.cshtml";
            public readonly string RecordTime = "~/Areas/Mobile/Views/Case/RecordTime.cshtml";
            public readonly string RecordTimeAdd = "~/Areas/Mobile/Views/Case/RecordTimeAdd.cshtml";
            public readonly string RecordTimeEdit = "~/Areas/Mobile/Views/Case/RecordTimeEdit.cshtml";
            public readonly string Search = "~/Areas/Mobile/Views/Case/Search.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CaseController : LALoDep.Areas.Mobile.Controllers.CaseController
    {
        public T4MVC_CaseController() : base(Dummy.Instance) { }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            SearchOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseSearchViewModel searchParams);

        [NonAction]
        public override System.Web.Mvc.JsonResult Search(LALoDep.Models.CaseSearchViewModel searchParams)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchParams", searchParams);
            SearchOverride(callInfo, searchParams);
            return callInfo;
        }

        [NonAction]
        partial void CaseInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult CaseInfo(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CaseInfoOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CaseAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CaseAdd()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseAdd);
            CaseAddOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CaseAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Areas.Mobile.Models.CaseAddViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CaseAdd(LALoDep.Areas.Mobile.Models.CaseAddViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CaseAdd);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            CaseAddOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void HearingAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult HearingAdd()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingAdd);
            HearingAddOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HearingAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Areas.Mobile.Models.HearingAddEditViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult HearingAdd(LALoDep.Areas.Mobile.Models.HearingAddEditViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingAdd);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            HearingAddOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void HearingEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult HearingEdit(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            HearingEditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void HearingEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Areas.Mobile.Models.HearingAddEditViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult HearingEdit(LALoDep.Areas.Mobile.Models.HearingAddEditViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            HearingEditOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void RecordTimeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RecordTime()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RecordTime);
            RecordTimeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RecordTimeAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RecordTimeAdd()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RecordTimeAdd);
            RecordTimeAddOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RecordTimeAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Areas.Mobile.Models.RecordTimeAddViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult RecordTimeAdd(LALoDep.Areas.Mobile.Models.RecordTimeAddViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RecordTimeAdd);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            RecordTimeAddOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void RecordTimeEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult RecordTimeEdit(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RecordTimeEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RecordTimeEditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RecordTimeEditSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Areas.Mobile.Models.RecordTimeEditViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult RecordTimeEditSave(LALoDep.Areas.Mobile.Models.RecordTimeEditViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RecordTimeEditSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            RecordTimeEditSaveOverride(callInfo, viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
