// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LALoDep.Controllers
{
    public partial class QHEController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected QHEController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHEHearing()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEHearing);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult QHEHearingUpdate()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QHEHearingUpdate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHEAttendance()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEAttendance);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult QHEAttendanceSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QHEAttendanceSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHEPlea()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEPlea);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHEPos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEPos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult HearingOpinion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingOpinion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult HearingOpinionSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.HearingOpinionSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHEFindingsAndOrders()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEFindingsAndOrders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteFindingsAndOrders()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteFindingsAndOrders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddFindingsAndOrders()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddFindingsAndOrders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditFindingsAndOrders()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditFindingsAndOrders);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHEAllegations()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEAllegations);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHENextHearing()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHENextHearing);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHERecordTime()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHERecordTime);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult QHERecordTimeList()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.QHERecordTimeList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RecordTimeDelete()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RecordTimeDelete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHERecordTimeAdd()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHERecordTimeAdd);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult QHERecordTimeAddSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QHERecordTimeAddSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QHERecordTimeEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHERecordTimeEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult QHERecordTimeEditSave()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QHERecordTimeEditSave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult NextQHECase()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NextQHECase);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public QHEController Actions { get { return MVC.QHE; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "QHE";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "QHE";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string QHEHearing = "QHEHearing";
            public readonly string QHEHearingUpdate = "QHEHearingUpdate";
            public readonly string QHEAttendance = "QHEAttendance";
            public readonly string QHEAttendanceSave = "QHEAttendanceSave";
            public readonly string QHEPlea = "QHEPlea";
            public readonly string QHEPos = "QHEPos";
            public readonly string HearingOpinion = "HearingOpinion";
            public readonly string HearingOpinionSave = "HearingOpinionSave";
            public readonly string QHEFindingsAndOrders = "QHEFindingsAndOrders";
            public readonly string DeleteFindingsAndOrders = "DeleteFindingsAndOrders";
            public readonly string AddFindingsAndOrders = "AddFindingsAndOrders";
            public readonly string EditFindingsAndOrders = "EditFindingsAndOrders";
            public readonly string QHEAllegations = "QHEAllegations";
            public readonly string QHENextHearing = "QHENextHearing";
            public readonly string QHERecordTime = "QHERecordTime";
            public readonly string QHERecordTimeList = "QHERecordTimeList";
            public readonly string RecordTimeDelete = "RecordTimeDelete";
            public readonly string QHERecordTimeAdd = "QHERecordTimeAdd";
            public readonly string QHERecordTimeAddSave = "QHERecordTimeAddSave";
            public readonly string QHERecordTimeEdit = "QHERecordTimeEdit";
            public readonly string QHERecordTimeEditSave = "QHERecordTimeEditSave";
            public readonly string NextQHECase = "NextQHECase";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string QHEHearing = "QHEHearing";
            public const string QHEHearingUpdate = "QHEHearingUpdate";
            public const string QHEAttendance = "QHEAttendance";
            public const string QHEAttendanceSave = "QHEAttendanceSave";
            public const string QHEPlea = "QHEPlea";
            public const string QHEPos = "QHEPos";
            public const string HearingOpinion = "HearingOpinion";
            public const string HearingOpinionSave = "HearingOpinionSave";
            public const string QHEFindingsAndOrders = "QHEFindingsAndOrders";
            public const string DeleteFindingsAndOrders = "DeleteFindingsAndOrders";
            public const string AddFindingsAndOrders = "AddFindingsAndOrders";
            public const string EditFindingsAndOrders = "EditFindingsAndOrders";
            public const string QHEAllegations = "QHEAllegations";
            public const string QHENextHearing = "QHENextHearing";
            public const string QHERecordTime = "QHERecordTime";
            public const string QHERecordTimeList = "QHERecordTimeList";
            public const string RecordTimeDelete = "RecordTimeDelete";
            public const string QHERecordTimeAdd = "QHERecordTimeAdd";
            public const string QHERecordTimeAddSave = "QHERecordTimeAddSave";
            public const string QHERecordTimeEdit = "QHERecordTimeEdit";
            public const string QHERecordTimeEditSave = "QHERecordTimeEditSave";
            public const string NextQHECase = "NextQHECase";
        }


        static readonly ActionParamsClass_QHEHearing s_params_QHEHearing = new ActionParamsClass_QHEHearing();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHEHearing QHEHearingParams { get { return s_params_QHEHearing; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHEHearing
        {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_QHEHearingUpdate s_params_QHEHearingUpdate = new ActionParamsClass_QHEHearingUpdate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHEHearingUpdate QHEHearingUpdateParams { get { return s_params_QHEHearingUpdate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHEHearingUpdate
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_QHEAttendance s_params_QHEAttendance = new ActionParamsClass_QHEAttendance();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHEAttendance QHEAttendanceParams { get { return s_params_QHEAttendance; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHEAttendance
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_QHEAttendanceSave s_params_QHEAttendanceSave = new ActionParamsClass_QHEAttendanceSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHEAttendanceSave QHEAttendanceSaveParams { get { return s_params_QHEAttendanceSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHEAttendanceSave
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_QHEPlea s_params_QHEPlea = new ActionParamsClass_QHEPlea();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHEPlea QHEPleaParams { get { return s_params_QHEPlea; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHEPlea
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_QHEPos s_params_QHEPos = new ActionParamsClass_QHEPos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHEPos QHEPosParams { get { return s_params_QHEPos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHEPos
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_HearingOpinion s_params_HearingOpinion = new ActionParamsClass_HearingOpinion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HearingOpinion HearingOpinionParams { get { return s_params_HearingOpinion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HearingOpinion
        {
            public readonly string id = "id";
            public readonly string opinionid = "opinionid";
            public readonly string enhearingID = "enhearingID";
            public readonly string ennoteID = "ennoteID";
            public readonly string enopinion = "enopinion";
        }
        static readonly ActionParamsClass_HearingOpinionSave s_params_HearingOpinionSave = new ActionParamsClass_HearingOpinionSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HearingOpinionSave HearingOpinionSaveParams { get { return s_params_HearingOpinionSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HearingOpinionSave
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_QHEFindingsAndOrders s_params_QHEFindingsAndOrders = new ActionParamsClass_QHEFindingsAndOrders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHEFindingsAndOrders QHEFindingsAndOrdersParams { get { return s_params_QHEFindingsAndOrders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHEFindingsAndOrders
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteFindingsAndOrders s_params_DeleteFindingsAndOrders = new ActionParamsClass_DeleteFindingsAndOrders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteFindingsAndOrders DeleteFindingsAndOrdersParams { get { return s_params_DeleteFindingsAndOrders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteFindingsAndOrders
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddFindingsAndOrders s_params_AddFindingsAndOrders = new ActionParamsClass_AddFindingsAndOrders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddFindingsAndOrders AddFindingsAndOrdersParams { get { return s_params_AddFindingsAndOrders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddFindingsAndOrders
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_EditFindingsAndOrders s_params_EditFindingsAndOrders = new ActionParamsClass_EditFindingsAndOrders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditFindingsAndOrders EditFindingsAndOrdersParams { get { return s_params_EditFindingsAndOrders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditFindingsAndOrders
        {
            public readonly string id = "id";
            public readonly string fId = "fId";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_QHEAllegations s_params_QHEAllegations = new ActionParamsClass_QHEAllegations();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHEAllegations QHEAllegationsParams { get { return s_params_QHEAllegations; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHEAllegations
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_QHENextHearing s_params_QHENextHearing = new ActionParamsClass_QHENextHearing();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHENextHearing QHENextHearingParams { get { return s_params_QHENextHearing; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHENextHearing
        {
            public readonly string id = "id";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_QHERecordTime s_params_QHERecordTime = new ActionParamsClass_QHERecordTime();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHERecordTime QHERecordTimeParams { get { return s_params_QHERecordTime; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHERecordTime
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_QHERecordTimeList s_params_QHERecordTimeList = new ActionParamsClass_QHERecordTimeList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHERecordTimeList QHERecordTimeListParams { get { return s_params_QHERecordTimeList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHERecordTimeList
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_RecordTimeDelete s_params_RecordTimeDelete = new ActionParamsClass_RecordTimeDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RecordTimeDelete RecordTimeDeleteParams { get { return s_params_RecordTimeDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RecordTimeDelete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_QHERecordTimeAdd s_params_QHERecordTimeAdd = new ActionParamsClass_QHERecordTimeAdd();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHERecordTimeAdd QHERecordTimeAddParams { get { return s_params_QHERecordTimeAdd; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHERecordTimeAdd
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_QHERecordTimeAddSave s_params_QHERecordTimeAddSave = new ActionParamsClass_QHERecordTimeAddSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHERecordTimeAddSave QHERecordTimeAddSaveParams { get { return s_params_QHERecordTimeAddSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHERecordTimeAddSave
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_QHERecordTimeEdit s_params_QHERecordTimeEdit = new ActionParamsClass_QHERecordTimeEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHERecordTimeEdit QHERecordTimeEditParams { get { return s_params_QHERecordTimeEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHERecordTimeEdit
        {
            public readonly string id = "id";
            public readonly string wId = "wId";
        }
        static readonly ActionParamsClass_QHERecordTimeEditSave s_params_QHERecordTimeEditSave = new ActionParamsClass_QHERecordTimeEditSave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QHERecordTimeEditSave QHERecordTimeEditSaveParams { get { return s_params_QHERecordTimeEditSave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QHERecordTimeEditSave
        {
            public readonly string viewModel = "viewModel";
            public readonly string oldViewModel = "oldViewModel";
        }
        static readonly ActionParamsClass_NextQHECase s_params_NextQHECase = new ActionParamsClass_NextQHECase();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NextQHECase NextQHECaseParams { get { return s_params_NextQHECase; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NextQHECase
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _partialRecordTimeList = "_partialRecordTimeList";
                public readonly string _steps = "_steps";
                public readonly string AddFindingsAndOrders = "AddFindingsAndOrders";
                public readonly string EditFindingsAndOrders = "EditFindingsAndOrders";
                public readonly string HearingOpinion = "HearingOpinion";
                public readonly string QHEAllegations = "QHEAllegations";
                public readonly string QHEAttendance = "QHEAttendance";
                public readonly string QHEFindingsAndOrders = "QHEFindingsAndOrders";
                public readonly string QHEHearing = "QHEHearing";
                public readonly string QHENextHearing = "QHENextHearing";
                public readonly string QHEPlea = "QHEPlea";
                public readonly string QHEPos = "QHEPos";
                public readonly string QHERecordTime = "QHERecordTime";
                public readonly string QHERecordTimeAdd = "QHERecordTimeAdd";
                public readonly string QHERecordTimeEdit = "QHERecordTimeEdit";
            }
            public readonly string _partialRecordTimeList = "~/Views/QHE/_partialRecordTimeList.cshtml";
            public readonly string _steps = "~/Views/QHE/_steps.cshtml";
            public readonly string AddFindingsAndOrders = "~/Views/QHE/AddFindingsAndOrders.cshtml";
            public readonly string EditFindingsAndOrders = "~/Views/QHE/EditFindingsAndOrders.cshtml";
            public readonly string HearingOpinion = "~/Views/QHE/HearingOpinion.cshtml";
            public readonly string QHEAllegations = "~/Views/QHE/QHEAllegations.cshtml";
            public readonly string QHEAttendance = "~/Views/QHE/QHEAttendance.cshtml";
            public readonly string QHEFindingsAndOrders = "~/Views/QHE/QHEFindingsAndOrders.cshtml";
            public readonly string QHEHearing = "~/Views/QHE/QHEHearing.cshtml";
            public readonly string QHENextHearing = "~/Views/QHE/QHENextHearing.cshtml";
            public readonly string QHEPlea = "~/Views/QHE/QHEPlea.cshtml";
            public readonly string QHEPos = "~/Views/QHE/QHEPos.cshtml";
            public readonly string QHERecordTime = "~/Views/QHE/QHERecordTime.cshtml";
            public readonly string QHERecordTimeAdd = "~/Views/QHE/QHERecordTimeAdd.cshtml";
            public readonly string QHERecordTimeEdit = "~/Views/QHE/QHERecordTimeEdit.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_QHEController : LALoDep.Controllers.QHEController
    {
        public T4MVC_QHEController() : base(Dummy.Instance) { }

        [NonAction]
        partial void QHEHearingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string page);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHEHearing(string id, string page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEHearing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            QHEHearingOverride(callInfo, id, page);
            return callInfo;
        }

        [NonAction]
        partial void QHEHearingUpdateOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.CaseOpening.HearingModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult QHEHearingUpdate(LALoDep.Models.CaseOpening.HearingModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QHEHearingUpdate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            QHEHearingUpdateOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void QHEAttendanceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHEAttendance(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEAttendance);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QHEAttendanceOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QHEAttendanceSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Case.AttendanceViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult QHEAttendanceSave(LALoDep.Models.Case.AttendanceViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QHEAttendanceSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            QHEAttendanceSaveOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void QHEPleaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHEPlea(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEPlea);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QHEPleaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QHEPleaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Case.PleaViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHEPlea(LALoDep.Models.Case.PleaViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEPlea);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            QHEPleaOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void QHEPosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHEPos(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEPos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QHEPosOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void HearingOpinionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string opinionid, string enhearingID, string ennoteID, string enopinion);

        [NonAction]
        public override System.Web.Mvc.ActionResult HearingOpinion(string id, string opinionid, string enhearingID, string ennoteID, string enopinion)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HearingOpinion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "opinionid", opinionid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "enhearingID", enhearingID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ennoteID", ennoteID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "enopinion", enopinion);
            HearingOpinionOverride(callInfo, id, opinionid, enhearingID, ennoteID, enopinion);
            return callInfo;
        }

        [NonAction]
        partial void HearingOpinionSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Case.HearingOpinionViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult HearingOpinionSave(LALoDep.Models.Case.HearingOpinionViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.HearingOpinionSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            HearingOpinionSaveOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void QHEFindingsAndOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHEFindingsAndOrders(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEFindingsAndOrders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QHEFindingsAndOrdersOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteFindingsAndOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteFindingsAndOrders(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteFindingsAndOrders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteFindingsAndOrdersOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddFindingsAndOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddFindingsAndOrders(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddFindingsAndOrders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddFindingsAndOrdersOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddFindingsAndOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Case.FindingsAndOrdersAddViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddFindingsAndOrders(LALoDep.Models.Case.FindingsAndOrdersAddViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddFindingsAndOrders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AddFindingsAndOrdersOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void EditFindingsAndOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string fId);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditFindingsAndOrders(string id, string fId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditFindingsAndOrders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fId", fId);
            EditFindingsAndOrdersOverride(callInfo, id, fId);
            return callInfo;
        }

        [NonAction]
        partial void EditFindingsAndOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Case.FindingsAndOrdersEditViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditFindingsAndOrders(LALoDep.Models.Case.FindingsAndOrdersEditViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditFindingsAndOrders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EditFindingsAndOrdersOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void QHEAllegationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHEAllegations(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEAllegations);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QHEAllegationsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QHEAllegationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.QHEAllegationViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHEAllegations(LALoDep.Models.QHEAllegationViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHEAllegations);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            QHEAllegationsOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void QHENextHearingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHENextHearing(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHENextHearing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QHENextHearingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QHENextHearingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.QHENextHearingSaveViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHENextHearing(LALoDep.Models.QHENextHearingSaveViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHENextHearing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            QHENextHearingOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void QHERecordTimeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHERecordTime(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHERecordTime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QHERecordTimeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QHERecordTimeListOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, LALoDep.Models.Case.RecordTimeViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult QHERecordTimeList(LALoDep.Models.Case.RecordTimeViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.QHERecordTimeList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            QHERecordTimeListOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void RecordTimeDeleteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.JsonResult RecordTimeDelete(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RecordTimeDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RecordTimeDeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QHERecordTimeAddOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHERecordTimeAdd(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHERecordTimeAdd);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QHERecordTimeAddOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QHERecordTimeAddSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Case.RecordTimeAddViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult QHERecordTimeAddSave(LALoDep.Models.Case.RecordTimeAddViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QHERecordTimeAddSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            QHERecordTimeAddSaveOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void QHERecordTimeEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string wId);

        [NonAction]
        public override System.Web.Mvc.ActionResult QHERecordTimeEdit(string id, string wId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QHERecordTimeEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "wId", wId);
            QHERecordTimeEditOverride(callInfo, id, wId);
            return callInfo;
        }

        [NonAction]
        partial void QHERecordTimeEditSaveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Case.RecordTimeEditViewModel viewModel, LALoDep.Models.Case.RecordTimeEditViewModel oldViewModel);

        [NonAction]
        public override System.Web.Mvc.JsonResult QHERecordTimeEditSave(LALoDep.Models.Case.RecordTimeEditViewModel viewModel, LALoDep.Models.Case.RecordTimeEditViewModel oldViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.QHERecordTimeEditSave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "oldViewModel", oldViewModel);
            QHERecordTimeEditSaveOverride(callInfo, viewModel, oldViewModel);
            return callInfo;
        }

        [NonAction]
        partial void NextQHECaseOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult NextQHECase(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.NextQHECase);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            NextQHECaseOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
