// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LALoDep.Controllers.Administration
{
    public partial class UsersController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UsersController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteUser()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteUserRole()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteUserRole);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult LoginInAs()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoginInAs);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PersonLegalNumbers()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PersonLegalNumbers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UserContact()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserContact);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Department()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Department);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveDepartment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDepartment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteDepartment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDepartment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadSignature()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadSignature);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveSignatureImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSignatureImage);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UsersController Actions { get { return MVC.Users; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Users";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Users";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Search = "Search";
            public readonly string AddEdit = "AddEdit";
            public readonly string DeleteUser = "DeleteUser";
            public readonly string DeleteUserRole = "DeleteUserRole";
            public readonly string LoginInAs = "LoginInAs";
            public readonly string PersonLegalNumbers = "PersonLegalNumbers";
            public readonly string UserContact = "UserContact";
            public readonly string Department = "Department";
            public readonly string SaveDepartment = "SaveDepartment";
            public readonly string DeleteDepartment = "DeleteDepartment";
            public readonly string UploadSignature = "UploadSignature";
            public readonly string SaveSignatureImage = "SaveSignatureImage";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Search = "Search";
            public const string AddEdit = "AddEdit";
            public const string DeleteUser = "DeleteUser";
            public const string DeleteUserRole = "DeleteUserRole";
            public const string LoginInAs = "LoginInAs";
            public const string PersonLegalNumbers = "PersonLegalNumbers";
            public const string UserContact = "UserContact";
            public const string Department = "Department";
            public const string SaveDepartment = "SaveDepartment";
            public const string DeleteDepartment = "DeleteDepartment";
            public const string UploadSignature = "UploadSignature";
            public const string SaveSignatureImage = "SaveSignatureImage";
        }


        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddEdit s_params_AddEdit = new ActionParamsClass_AddEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddEdit AddEditParams { get { return s_params_AddEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddEdit
        {
            public readonly string jcatsUserID = "jcatsUserID";
            public readonly string personID = "personID";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteUser s_params_DeleteUser = new ActionParamsClass_DeleteUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams { get { return s_params_DeleteUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser
        {
            public readonly string userId = "userId";
        }
        static readonly ActionParamsClass_DeleteUserRole s_params_DeleteUserRole = new ActionParamsClass_DeleteUserRole();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUserRole DeleteUserRoleParams { get { return s_params_DeleteUserRole; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUserRole
        {
            public readonly string roleId = "roleId";
        }
        static readonly ActionParamsClass_LoginInAs s_params_LoginInAs = new ActionParamsClass_LoginInAs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoginInAs LoginInAsParams { get { return s_params_LoginInAs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoginInAs
        {
            public readonly string username = "username";
        }
        static readonly ActionParamsClass_PersonLegalNumbers s_params_PersonLegalNumbers = new ActionParamsClass_PersonLegalNumbers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PersonLegalNumbers PersonLegalNumbersParams { get { return s_params_PersonLegalNumbers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PersonLegalNumbers
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UserContact s_params_UserContact = new ActionParamsClass_UserContact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserContact UserContactParams { get { return s_params_UserContact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserContact
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Department s_params_Department = new ActionParamsClass_Department();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Department DepartmentParams { get { return s_params_Department; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Department
        {
            public readonly string id = "id";
            public readonly string deptId = "deptId";
        }
        static readonly ActionParamsClass_SaveDepartment s_params_SaveDepartment = new ActionParamsClass_SaveDepartment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveDepartment SaveDepartmentParams { get { return s_params_SaveDepartment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveDepartment
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_DeleteDepartment s_params_DeleteDepartment = new ActionParamsClass_DeleteDepartment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteDepartment DeleteDepartmentParams { get { return s_params_DeleteDepartment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteDepartment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UploadSignature s_params_UploadSignature = new ActionParamsClass_UploadSignature();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadSignature UploadSignatureParams { get { return s_params_UploadSignature; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadSignature
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SaveSignatureImage s_params_SaveSignatureImage = new ActionParamsClass_SaveSignatureImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveSignatureImage SaveSignatureImageParams { get { return s_params_SaveSignatureImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveSignatureImage
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AddEdit = "AddEdit";
                public readonly string Department = "Department";
                public readonly string PersonLegalNumbers = "PersonLegalNumbers";
                public readonly string Search = "Search";
                public readonly string UploadSignature = "UploadSignature";
                public readonly string UserContact = "UserContact";
            }
            public readonly string AddEdit = "~/Views/Users/AddEdit.cshtml";
            public readonly string Department = "~/Views/Users/Department.cshtml";
            public readonly string PersonLegalNumbers = "~/Views/Users/PersonLegalNumbers.cshtml";
            public readonly string Search = "~/Views/Users/Search.cshtml";
            public readonly string UploadSignature = "~/Views/Users/UploadSignature.cshtml";
            public readonly string UserContact = "~/Views/Users/UserContact.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UsersController : LALoDep.Controllers.Administration.UsersController
    {
        public T4MVC_UsersController() : base(Dummy.Instance) { }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            SearchOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Administration.UsersViewModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult Search(LALoDep.Models.Administration.UsersViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SearchOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AddEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string jcatsUserID, string personID);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddEdit(string jcatsUserID, string personID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jcatsUserID", jcatsUserID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "personID", personID);
            AddEditOverride(callInfo, jcatsUserID, personID);
            return callInfo;
        }

        [NonAction]
        partial void AddEditOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, LALoDep.Models.Administration.UserAddEditViewModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddEdit(LALoDep.Models.Administration.UserAddEditViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddEditOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int userId);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteUser(int userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            DeleteUserOverride(callInfo, userId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteUserRoleOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int roleId);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteUserRole(int roleId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteUserRole);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "roleId", roleId);
            DeleteUserRoleOverride(callInfo, roleId);
            return callInfo;
        }

        [NonAction]
        partial void LoginInAsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string username);

        [NonAction]
        public override System.Web.Mvc.JsonResult LoginInAs(string username)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoginInAs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
            LoginInAsOverride(callInfo, username);
            return callInfo;
        }

        [NonAction]
        partial void PersonLegalNumbersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PersonLegalNumbers(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PersonLegalNumbers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PersonLegalNumbersOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UserContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserContact(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserContact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            UserContactOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DepartmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string deptId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Department(string id, string deptId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Department);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deptId", deptId);
            DepartmentOverride(callInfo, id, deptId);
            return callInfo;
        }

        [NonAction]
        partial void SaveDepartmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Administration.UserDepartmentViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveDepartment(LALoDep.Models.Administration.UserDepartmentViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDepartment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            SaveDepartmentOverride(callInfo, viewModel);
            return callInfo;
        }

        [NonAction]
        partial void DeleteDepartmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteDepartment(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDepartment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteDepartmentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UploadSignatureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadSignature(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadSignature);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            UploadSignatureOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SaveSignatureImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, LALoDep.Models.Administration.UploadSignatureViewModel viewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveSignatureImage(LALoDep.Models.Administration.UploadSignatureViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSignatureImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            SaveSignatureImageOverride(callInfo, viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
